const vendorIds = {
    "08de": "???	Vendor Devices",
    "18f8": "[Maxxter]	Vendor Devices",
    "1c87": "2N TELEKOMUNIKACE a.s.	Vendor Devices",
    "1630": "2Wire, Inc.	Vendor Devices",
    "08c8": "2Wire, Inc.	Vendor Devices",
    "6891": "3Com	Vendor Devices",
    "a727": "3Com	Vendor Devices",
    "0506": "3Com Corp.	Vendor Devices",
    "256f": "3Dconnexion	Vendor Devices",
    "05bc": "3G Green Green Globe Co., Ltd	Vendor Devices",
    "0e35": "3Pea Technologies, Inc.	Vendor Devices",
    "189f": "3Shape A/S	Vendor Devices",
    "29e8": "4Links Limited	Vendor Devices",
    "1737": "802.11g Adapter [Linksys WUSB54GC v3]	Vendor Devices",
    "3171": "8086 Consultancy	Vendor Devices",
    "2dc8": "8BitDo	Vendor Devices",
    "228d": "8D Technologies inc.	Vendor Devices",
    "125f": "A-DATA Technology Co., Ltd.	Vendor Devices",
    "13d1": "A-Max Technology Macao Commercial Offshore Co. Ltd.	Vendor Devices",
    "0874": "A-Tec Subsystem, Inc.	Vendor Devices",
    "059c": "A-Trend Technology Co., Ltd	Vendor Devices",
    "1afe": "A. Eberle GmbH & Co. KG	Vendor Devices",
    "0dbc": "A&D Medical	Vendor Devices",
    "09da": "A4Tech Co., Ltd.	Vendor Devices",
    "0fb9": "AACom Corp.	Vendor Devices",
    "06d6": "Aashima Technology B.V.	Vendor Devices",
    "1a61": "Abbott Diabetes Care	Vendor Devices",
    "1ba6": "Abilis Systems	Vendor Devices",
    "1419": "ABILITY ENTERPRISE CO., LTD.	Vendor Devices",
    "0ec1": "Abit Computer Corp.	Vendor Devices",
    "0794": "ABL Electronics Corp.	Vendor Devices",
    "07b8": "AboCom Systems Inc	Vendor Devices",
    "0678": "ACard Technology Corp.	Vendor Devices",
    "04e4": "ACC Microelectronics	Vendor Devices",
    "1ca0": "ACCARIO Inc.	Vendor Devices",
    "1605": "ACCES I/O Products, Inc.	Vendor Devices",
    "8070": "ACCES I/O Products, Inc.	Vendor Devices",
    "0fed": "Access Co., Ltd	Vendor Devices",
    "0db5": "Access IS	Vendor Devices",
    "0dd0": "Access Solutions	Vendor Devices",
    "083a": "Accton Technology Corp.	Vendor Devices",
    "0460": "Ace Cad Enterprise Co., Ltd	Vendor Devices",
    "4766": "Aceeca	Vendor Devices",
    "049c": "Acer Advanced Labs, Inc.	Vendor Devices",
    "1189": "Acer Communications & Multimedia	Vendor Devices",
    "0967": "Acer NeWeb Corp.	Vendor Devices",
    "04a5": "Acer Peripherals Inc. (now BenQ Corp.)	Vendor Devices",
    "066e": "Acer Semiconductor America, Inc.	Vendor Devices",
    "5986": "Acer, Inc	Vendor Devices",
    "0502": "Acer, Inc.	Vendor Devices",
    "042e": "Acer, Inc.	Vendor Devices",
    "1cb3": "Aces Electronic Co., Ltd.	Vendor Devices",
    "0f13": "Acetek Technology Co., Ltd	Vendor Devices",
    "1990": "Acron Precision Industrial Co., Ltd.	Vendor Devices",
    "24ff": "Acroname Inc.	Vendor Devices",
    "0f62": "Acrox Technologies Co., Ltd	Vendor Devices",
    "1a34": "ACRUX	Vendor Devices",
    "0c6a": "ACS	Vendor Devices",
    "061c": "Act Labs, Ltd	Vendor Devices",
    "0515": "ACTC	Vendor Devices",
    "1514": "Actel	Vendor Devices",
    "1a41": "Action Electronics Co., Ltd.	Vendor Devices",
    "0835": "Action Star Enterprise Co., Ltd	Vendor Devices",
    "1de1": "Actions Microelectronics Co.	Vendor Devices",
    "10d6": "Actions Semiconductor Co., Ltd	Vendor Devices",
    "2101": "ActionStar	Vendor Devices",
    "0684": "Actiontec Electronics, Inc.	Vendor Devices",
    "1668": "Actiontec Electronics, Inc. [hex]	Vendor Devices",
    "09c4": "ACTiSYS Corp.	Vendor Devices",
    "0e5a": "Active Co., Ltd	Vendor Devices",
    "0e5a": "Active Co., Ltd	Vendor Devices",
    "0854": "ActiveWire, Inc.	Vendor Devices",
    "0647": "Acton Research Corp.	Vendor Devices",
    "239a": "Adafruit	Vendor Devices",
    "03f3": "Adaptec, Inc.	Vendor Devices",
    "1c21": "ADDMM LLC	Vendor Devices",
    "09df": "Addonics Technologies Corp.	Vendor Devices",
    "0bf6": "Addonics Technologies, Inc.	Vendor Devices",
    "087c": "Adesso/Kbtek America, Inc.	Vendor Devices",
    "0422": "ADI Systems, Inc.	Vendor Devices",
    "0976": "Adirondack Wire & Cable	Vendor Devices",
    "0b63": "ADLink Technology, Inc.	Vendor Devices",
    "07a6": "ADMtek, Inc.	Vendor Devices",
    "0459": "Adobe Systems, Inc.	Vendor Devices",
    "0627": "Adomax Technology Co., Ltd	Vendor Devices",
    "1cd4": "adp corporation	Vendor Devices",
    "06e1": "ADS Technologies, Inc.	Vendor Devices",
    "0e9b": "ADTEC Corp.	Vendor Devices",
    "0e98": "Advanced Analogic Technologies, Inc.	Vendor Devices",
    "072f": "Advanced Card Systems, Ltd	Vendor Devices",
    "0522": "Advanced Connectek, Inc.	Vendor Devices",
    "17a5": "Advanced Connection Technology Inc.	Vendor Devices",
    "0b89": "Advanced Digital Broadcast, Ltd	Vendor Devices",
    "0428": "Advanced Gravis Computer Tech, Ltd	Vendor Devices",
    "059d": "Advanced Input Devices	Vendor Devices",
    "0438": "Advanced Micro Devices, Inc.	Vendor Devices",
    "0479": "Advanced Peripheral Laboratories	Vendor Devices",
    "2149": "Advanced Silicon S.A.	Vendor Devices",
    "0d67": "Advanet, Inc.	Vendor Devices",
    "1809": "Advantech	Vendor Devices",
    "3334": "AEI	Vendor Devices",
    "0476": "AESP	Vendor Devices",
    "2443": "Aessent Technology Ltd	Vendor Devices",
    "0659": "Aethra	Vendor Devices",
    "1b80": "Afatech	Vendor Devices",
    "15a4": "Afatech Technologies, Inc.	Vendor Devices",
    "2576": "AFO Co., Ltd.	Vendor Devices",
    "0c08": "Agate	Vendor Devices",
    "21d6": "Agecodagis SARL	Vendor Devices",
    "0d4e": "Agere Systems Netherland BV	Vendor Devices",
    "047e": "Agere Systems, Inc. (Lucent)	Vendor Devices",
    "06bd": "AGFA-Gevaert NV	Vendor Devices",
    "326d": "Agile Display Solutions Co., Ltd	Vendor Devices",
    "0957": "Agilent Technologies, Inc.	Vendor Devices",
    "c502": "AGPTek	Vendor Devices",
    "0ef1": "Aichi Micro Intelligent Corp.	Vendor Devices",
    "1633": "AIM GmbH	Vendor Devices",
    "09dc": "Aimex Corp.	Vendor Devices",
    "12fd": "AIN Comm. Technology Co., Ltd	Vendor Devices",
    "08ca": "Aiptek International, Inc.	Vendor Devices",
    "0fe2": "Air Techniques	Vendor Devices",
    "0521": "Airborn Connectors	Vendor Devices",
    "1e8e": "Airbus Defence and Space	Vendor Devices",
    "162a": "Airgo Networks Inc.	Vendor Devices",
    "0f3d": "Airprime, Incorporated	Vendor Devices",
    "0d33": "AirSpeak, Inc.	Vendor Devices",
    "1eda": "AirTies Wireless Networks	Vendor Devices",
    "124a": "AirVast	Vendor Devices",
    "0667": "Aiwa Co., Ltd	Vendor Devices",
    "0677": "Aiwa Co., Ltd	Vendor Devices",
    "0a2c": "AK-Modul-Bus Computer GmbH	Vendor Devices",
    "09e8": "AKAI Professional M.I. Corp.	Vendor Devices",
    "0a89": "Aktiv	Vendor Devices",
    "0529": "Aladdin Knowledge Systems	Vendor Devices",
    "24dc": "Aladdin R.D.	Vendor Devices",
    "0620": "Alaris, Inc.	Vendor Devices",
    "0910": "Alation Systems, Inc.	Vendor Devices",
    "11f7": "Alcatel (?)	Vendor Devices",
    "06e4": "Alcatel Microelectronics	Vendor Devices",
    "0533": "Alcatel Mobile Phones	Vendor Devices",
    "06b9": "Alcatel Telecom	Vendor Devices",
    "3200": "Alcatel-Lucent Enterprise	Vendor Devices",
    "1914": "Alco Digital Devices Limited	Vendor Devices",
    "058f": "Alcor Micro Corp.	Vendor Devices",
    "1c13": "ALECTRONIC LIMITED	Vendor Devices",
    "1f84": "Alere, Inc.	Vendor Devices",
    "13dc": "ALEREON, INC.	Vendor Devices",
    "13b2": "Alesis	Vendor Devices",
    "079d": "Alfadata Computer Corp.	Vendor Devices",
    "0c4a": "ALGE-TIMING GmbH	Vendor Devices",
    "0402": "ALi Corp.	Vendor Devices",
    "187c": "Alienware Corporation	Vendor Devices",
    "1f6f": "Aliph	Vendor Devices",
    "07e6": "Allied Cable Corp.	Vendor Devices",
    "069f": "Allied Data Technologies BV	Vendor Devices",
    "0caa": "Allied Telesis KK.	Vendor Devices",
    "07c9": "Allied Telesyn International	Vendor Devices",
    "1ab2": "Allied Vision	Vendor Devices",
    "0ae3": "Allion Computer, Inc.	Vendor Devices",
    "1570": "ALLTOP TECHNOLOGY CO., LTD.	Vendor Devices",
    "1f3a": "Allwinner Technology	Vendor Devices",
    "114d": "Alpha Imaging Technology Corp.	Vendor Devices",
    "1d14": "ALPHA-SAT TECHNOLOGY LIMITED	Vendor Devices",
    "081e": "AlphaSmart, Inc.	Vendor Devices",
    "1c98": "ALPINE ELECTRONICS, INC.	Vendor Devices",
    "044e": "Alps Electric Co., Ltd	Vendor Devices",
    "048c": "Alps Electric Ireland, Ltd	Vendor Devices",
    "0433": "Alps Electric, Inc.	Vendor Devices",
    "04d2": "Altec Lansing Technologies	Vendor Devices",
    "143c": "Altek Corporation	Vendor Devices",
    "09fb": "Altera	Vendor Devices",
    "0799": "Altera	Vendor Devices",
    "1b8c": "Altium Limited	Vendor Devices",
    "09b3": "Altius Solutions, Inc.	Vendor Devices",
    "0527": "ALTRA	Vendor Devices",
    "0f55": "AmbiCom, Inc.	Vendor Devices",
    "07e1": "Ambient Technologies, Inc.	Vendor Devices",
    "2aec": "Ambiq Micro, Inc.	Vendor Devices",
    "0bb2": "Ambit Microsystems Corp.	Vendor Devices",
    "104c": "AMCO TEC International, Inc.	Vendor Devices",
    "06be": "AME Optimedia Technology Co., Ltd	Vendor Devices",
    "0587": "America Kotobuki Electronics Industries, Inc.	Vendor Devices",
    "0929": "American Biometric Co.	Vendor Devices",
    "0d7e": "American Computer & Digital Components	Vendor Devices",
    "046b": "American Megatrends, Inc.	Vendor Devices",
    "0530": "American Microsystems, Inc.	Vendor Devices",
    "051d": "American Power Conversion	Vendor Devices",
    "0ee2": "AMI Semiconductor, Inc.	Vendor Devices",
    "0e0b": "Amigo Technology Inc.	Vendor Devices",
    "18c5": "AMIT Technology, Inc.	Vendor Devices",
    "0729": "Amitm	Vendor Devices",
    "1b8e": "Amlogic, Inc.	Vendor Devices",
    "1614": "Amoi Electronics	Vendor Devices",
    "0464": "AMP/Tycoelectronics Corp.	Vendor Devices",
    "0cca": "Amphenol	Vendor Devices",
    "1a25": "Amphenol East Asia Ltd.	Vendor Devices",
    "1ce1": "Amphenol KAE	Vendor Devices",
    "1325": "ams AG	Vendor Devices",
    "1c73": "AMT	Vendor Devices",
    "1ecb": "AMTelecom	Vendor Devices",
    "0774": "AmTRAN Technology Co., Ltd	Vendor Devices",
    "2520": "ANA-U GmbH	Vendor Devices",
    "1110": "Analog Devices Canada, Ltd (Allied Telesyn)	Vendor Devices",
    "0456": "Analog Devices, Inc.	Vendor Devices",
    "064b": "Analog Devices, Inc. (White Mountain DSP)	Vendor Devices",
    "0555": "ANAM S&T Co., Ltd	Vendor Devices",
    "0605": "Anchor C&C Co., Ltd	Vendor Devices",
    "0547": "Anchor Chips, Inc.	Vendor Devices",
    "0d6b": "And-Or Logic	Vendor Devices",
    "0d2f": "Andamiro	Vendor Devices",
    "1cfc": "ANDES TECHNOLOGY CORPORATION	Vendor Devices",
    "136e": "Andor Technology Ltd.	Vendor Devices",
    "08a8": "Andrea Electronics	Vendor Devices",
    "0bd7": "Andrew Pargeter & Associates	Vendor Devices",
    "a128": "AnMo Electronics Corp. / Dino-Lite (?)	Vendor Devices",
    "a168": "AnMo Electronics Corporation	Vendor Devices",
    "04ed": "Annabooks	Vendor Devices",
    "1cd6": "Antonio Precise Products Manufactory Ltd.	Vendor Devices",
    "10fd": "Anubis Electronics, Ltd	Vendor Devices",
    "16d5": "AnyDATA Corporation	Vendor Devices",
    "05f6": "AOC International	Vendor Devices",
    "0fff": "Aopen, Inc.	Vendor Devices",
    "0fff": "Aopen, Inc.	Vendor Devices",
    "1005": "Apacer Technology, Inc.	Vendor Devices",
    "224f": "APDM	Vendor Devices",
    "07c5": "APG Cash Drawer	Vendor Devices",
    "ab12": "aplic	Vendor Devices",
    "0e96": "Aplux Communications, Ltd	Vendor Devices",
    "0c60": "Apogee Electronics Corp.	Vendor Devices",
    "125c": "Apogee Inc.	Vendor Devices",
    "0c05": "Appian Graphics	Vendor Devices",
    "05ac": "Apple, Inc.	Vendor Devices",
    "0c8f": "Applied Microsystems	Vendor Devices",
    "0984": "Apricorn	Vendor Devices",
    "1ad4": "APS	Vendor Devices",
    "0880": "APT Technologies, Inc.	Vendor Devices",
    "07d2": "Aptio Products, Inc.	Vendor Devices",
    "12d8": "Araneus Information Systems Oy	Vendor Devices",
    "07da": "Arasan Chip Systems	Vendor Devices",
    "142b": "Arbiter Systems, Inc.	Vendor Devices",
    "05a3": "ARC International	Vendor Devices",
    "25c4": "ARCAM	Vendor Devices",
    "0e79": "Archos, Inc.	Vendor Devices",
    "0e79": "Archos, Inc.	Vendor Devices",
    "2341": "Arduino SA	Vendor Devices",
    "09f5": "AresCom	Vendor Devices",
    "25a7": "Areson Technology Corp	Vendor Devices",
    "0840": "Argosy Research, Inc.	Vendor Devices",
    "1b52": "ARH Inc.	Vendor Devices",
    "0706": "Ariel Corp.	Vendor Devices",
    "113c": "Arin Tech Co., Ltd	Vendor Devices",
    "126c": "Aristocrat Technologies	Vendor Devices",
    "071e": "Ariston Technologies	Vendor Devices",
    "18ec": "Arkmicro Technologies Inc.	Vendor Devices",
    "6547": "Arkmicro Technologies Inc.	Vendor Devices",
    "107d": "Arlec Australia, Ltd	Vendor Devices",
    "1776": "Arowana	Vendor Devices",
    "0d14": "Array Comm, Inc.	Vendor Devices",
    "09c1": "Arris Interactive LLC	Vendor Devices",
    "0ab0": "Arrow Strong Electronics Co., Ltd	Vendor Devices",
    "1707": "ARTIMI	Vendor Devices",
    "1c75": "Arturia	Vendor Devices",
    "2626": "Aruba Networks	Vendor Devices",
    "0556": "Asahi Kasei Microsystems Co., Ltd	Vendor Devices",
    "0b49": "ASCII Corp.	Vendor Devices",
    "0cae": "Ascom Business Systems, Ltd	Vendor Devices",
    "0d8b": "Ascom Telecommunications, Ltd	Vendor Devices",
    "0d40": "Ascor, Inc.	Vendor Devices",
    "2433": "ASETEK	Vendor Devices",
    "0b95": "ASIX Electronics Corp.	Vendor Devices",
    "a600": "ASIX s.r.o.	Vendor Devices",
    "0d55": "ASKA Technologies, Inc.	Vendor Devices",
    "069a": "Askey Computer Corp.	Vendor Devices",
    "1690": "Askey Computer Corp. [hex]	Vendor Devices",
    "174c": "ASMedia Technology Inc.	Vendor Devices",
    "2245": "Aspeed Technology, Inc.	Vendor Devices",
    "1849": "ASRock Incorporation	Vendor Devices",
    "2554": "ASSA ABLOY AB	Vendor Devices",
    "0bbc": "Assistive Technology, Inc.	Vendor Devices",
    "0418": "AST Research	Vendor Devices",
    "9886": "Astro Gaming	Vendor Devices",
    "0b7d": "Astrodesign, Inc.	Vendor Devices",
    "0d0c": "Astron Electronics Co., Ltd	Vendor Devices",
    "1c8e": "ASTRON INTERNATIONAL CORP.	Vendor Devices",
    "1d27": "ASUS	Vendor Devices",
    "0486": "ASUS Computers, Inc.	Vendor Devices",
    "0735": "Asuscom Network	Vendor Devices",
    "2821": "ASUSTek Computer Inc.	Vendor Devices",
    "0b05": "ASUSTek Computer, Inc.	Vendor Devices",
    "1761": "ASUSTek Computer, Inc. (wrong ID)	Vendor Devices",
    "178e": "ASUSTek Computer, Inc. (wrong ID)	Vendor Devices",
    "06f9": "ASYST electronic d.o.o.	Vendor Devices",
    "0467": "AT&T Paradyne	Vendor Devices",
    "11b0": "ATECH FLASH TECHNOLOGY	Vendor Devices",
    "0523": "ATEN GmbH	Vendor Devices",
    "0557": "ATEN International Co., Ltd	Vendor Devices",
    "1b72": "ATERGI TECHNOLOGY CO., LTD.	Vendor Devices",
    "0dc3": "Athena Smartcard Solutions, Inc.	Vendor Devices",
    "168c": "Atheros Communications	Vendor Devices",
    "1787": "ATI AIB	Vendor Devices",
    "0528": "ATI Technologies, Inc.	Vendor Devices",
    "0fa4": "ATL Technology	Vendor Devices",
    "1029": "Atlantic Coast Telesys	Vendor Devices",
    "03eb": "Atmel Corp.	Vendor Devices",
    "14af": "ATP Electronics Inc.	Vendor Devices",
    "1c82": "Atracsys	Vendor Devices",
    "f4ec": "Atten Electronics / Siglent Technologies	Vendor Devices",
    "060d": "Auctor Corp.	Vendor Devices",
    "0b99": "Audio International, Inc.	Vendor Devices",
    "0909": "Audio-Technica Corp.	Vendor Devices",
    "2912": "Audioengine	Vendor Devices",
    "21b4": "AudioQuest	Vendor Devices",
    "09bf": "Auerswald GmbH & Co. KG	Vendor Devices",
    "0755": "Aureal Semiconductor	Vendor Devices",
    "10de": "Authenex, Inc.	Vendor Devices",
    "08ff": "AuthenTec, Inc.	Vendor Devices",
    "1c37": "Authorizer Technologies, Inc.	Vendor Devices",
    "12c4": "Autocue Group Ltd	Vendor Devices",
    "100a": "AV Chaseway, Ltd	Vendor Devices",
    "192f": "Avago Technologies, Pte.	Vendor Devices",
    "0d9e": "Avaya	Vendor Devices",
    "05ef": "AVB, Inc. [anko?]	Vendor Devices",
    "1871": "Aveo Technology Corp.	Vendor Devices",
    "2574": "AVer Information, Inc.	Vendor Devices",
    "50c2": "Averatec (?)	Vendor Devices",
    "07ca": "AVerMedia Technologies, Inc.	Vendor Devices",
    "052d": "Avid Electronics Corp.	Vendor Devices",
    "0b0f": "AVID Technology	Vendor Devices",
    "0638": "Avision, Inc.	Vendor Devices",
    "1bc5": "AVIXE Technology (China) Ltd.	Vendor Devices",
    "0d56": "AVLAB Technology, Inc.	Vendor Devices",
    "057c": "AVM GmbH	Vendor Devices",
    "170d": "Avnera	Vendor Devices",
    "0624": "Avocent Corp.	Vendor Devices",
    "0412": "Award Software International	Vendor Devices",
    "0ec3": "Axell Co., Ltd	Vendor Devices",
    "1726": "Axesstel, Inc.	Vendor Devices",
    "05d9": "Axiohm Transaction Solutions	Vendor Devices",
    "0792": "Axis Communications AB	Vendor Devices",
    "1400": "Axxion Group Corp.	Vendor Devices",
    "0509": "Aztech Systems, Ltd	Vendor Devices",
    "19b5": "B & W Group	Vendor Devices",
    "07c8": "B.U.G., Inc.	Vendor Devices",
    "0856": "B&B Electronics	Vendor Devices",
    "0af7": "B2C2, Inc.	Vendor Devices",
    "0ca5": "BAE Systems Canada, Inc.	Vendor Devices",
    "0576": "BAFO/Quality Computer Accessories	Vendor Devices",
    "0ec4": "Ballracing Developments, Ltd	Vendor Devices",
    "13ad": "Baltech	Vendor Devices",
    "1a8d": "BandRich, Inc.	Vendor Devices",
    "0cd4": "Bang Olufsen	Vendor Devices",
    "1166": "Bantam Interactive Technologies	Vendor Devices",
    "0600": "Barco Display Systems	Vendor Devices",
    "2707": "Bardac Corporation	Vendor Devices",
    "2a6e": "Bare Conductive	Vendor Devices",
    "2080": "Barnes & Noble	Vendor Devices",
    "0aa9": "Baromtec Co.	Vendor Devices",
    "097f": "Barun Electronics Co., Ltd	Vendor Devices",
    "2555": "Basis Science Inc.	Vendor Devices",
    "2676": "Basler AG	Vendor Devices",
    "19b2": "Batronix	Vendor Devices",
    "09f9": "Bay Associates	Vendor Devices",
    "1a79": "Bayer Health Care LLC	Vendor Devices",
    "0de0": "BD Consumer Healthcare	Vendor Devices",
    "0de0": "BD Consumer Healthcare	Vendor Devices",
    "07a4": "Be, Inc.	Vendor Devices",
    "198f": "Beceem Communications Inc.	Vendor Devices",
    "0978": "Beckhoff GmbH	Vendor Devices",
    "046e": "Behavior Tech. Computer Corp.	Vendor Devices",
    "6000": "Beholder International Ltd.	Vendor Devices",
    "1397": "BEHRINGER International GmbH	Vendor Devices",
    "255e": "Beijing Bonxeon Technology Co., Ltd.	Vendor Devices",
    "3037": "Beijing Chushifengmang Technology Development Co.,Ltd.	Vendor Devices",
    "0b57": "Beijing HanwangTechnology Co., Ltd	Vendor Devices",
    "31c9": "BeiJing LanXum Computer Technology Co., Ltd.	Vendor Devices",
    "1bc0": "Beijing Senseshield Technology Co.,Ltd.	Vendor Devices",
    "7373": "Beijing STONE Technology Co. Ltd.	Vendor Devices",
    "2feb": "Beijing Veikk E-Commerce Co., Ltd.	Vendor Devices",
    "126d": "Bel Stewart	Vendor Devices",
    "15ec": "Belcarra Technologies Corp.	Vendor Devices",
    "1241": "Belkin	Vendor Devices",
    "050d": "Belkin Components	Vendor Devices",
    "1293": "Belkin Components [hex]	Vendor Devices",
    "1a08": "Bellwood International, Inc.	Vendor Devices",
    "199f": "Benica Corporation	Vendor Devices",
    "0a6e": "Benwin	Vendor Devices",
    "0c98": "Berkshire Products, Inc.	Vendor Devices",
    "03da": "Bernd Walter Computer Technology	Vendor Devices",
    "9849": "Bestmedia CD Recordable GmbH & Co. KG	Vendor Devices",
    "11c0": "Betop	Vendor Devices",
    "12d7": "BETTER WIRE FACTORY CO., LTD.	Vendor Devices",
    "1bd5": "BG Systems, Inc.	Vendor Devices",
    "23a0": "BIFIT	Vendor Devices",
    "19a8": "Biforst Technology Inc.	Vendor Devices",
    "146b": "BigBen Interactive	Vendor Devices",
    "0c56": "Billion Bright, Ltd	Vendor Devices",
    "08dd": "Billionton Systems, Inc.	Vendor Devices",
    "0614": "Bio-Rad Laboratories	Vendor Devices",
    "097e": "Biopac Systems Inc.	Vendor Devices",
    "04fb": "Biostar Microtech International Corp.	Vendor Devices",
    "25dd": "Bit4id Srl	Vendor Devices",
    "0e5c": "Bitland Information Technology Co., Ltd	Vendor Devices",
    "2366": "Bitmanufaktur GmbH	Vendor Devices",
    "0964": "BITRAN	Vendor Devices",
    "1520": "Bitwire Corp.	Vendor Devices",
    "0fbb": "Bitwise Systems, Inc.	Vendor Devices",
    "1a36": "Biwin Technology Ltd.	Vendor Devices",
    "1504": "Bixolon CO LTD	Vendor Devices",
    "1168": "BizConn International Corp.	Vendor Devices",
    "06c4": "Bizlink International Corp.	Vendor Devices",
    "1edb": "Blackmagic design	Vendor Devices",
    "27d4": "Blackstar Amplification Limited	Vendor Devices",
    "1188": "Bloomberg L.P.	Vendor Devices",
    "b58e": "Blue Microphones	Vendor Devices",
    "2458": "Bluegiga Technologies	Vendor Devices",
    "30a4": "Blues Wireless	Vendor Devices",
    "1706": "BlueView Technologies, Inc.	Vendor Devices",
    "1b0e": "BLUTRONICS S.r.l.	Vendor Devices",
    "09ca": "BMC Messsysteme GmbH	Vendor Devices",
    "0d13": "BMF Corp.	Vendor Devices",
    "1054": "BMS International Beheer N.V.	Vendor Devices",
    "0885": "Boca Research, Inc.	Vendor Devices",
    "0a43": "Boca Systems, Inc.	Vendor Devices",
    "1ccd": "Bodatong Technology (Shenzhen) Co., Ltd.	Vendor Devices",
    "19ab": "Bodelin	Vendor Devices",
    "0085": "Boeye Technology Co., Ltd.	Vendor Devices",
    "05a7": "Bose Corp.	Vendor Devices",
    "06fd": "Boston Acoustics	Vendor Devices",
    "3016": "Boundary Devices, LLC	Vendor Devices",
    "1402": "Bowe Bell & Howell	Vendor Devices",
    "0e2e": "Brady Worldwide, Inc.	Vendor Devices",
    "1234": "Brain Actuated Technologies	Vendor Devices",
    "05d1": "Brainboxes, Ltd	Vendor Devices",
    "0c9c": "Brand Innovators BV	Vendor Devices",
    "0607": "Bridge Information Co., Ltd	Vendor Devices",
    "1108": "Brightcom Technologies, Ltd	Vendor Devices",
    "0599": "Brilliance Semiconductor, Inc.	Vendor Devices",
    "078e": "Brincom, Inc.	Vendor Devices",
    "0a5c": "Broadcom Corp.	Vendor Devices",
    "4317": "Broadcom Corp.	Vendor Devices",
    "0827": "BroadLogic, Inc.	Vendor Devices",
    "0cc9": "BroadMAX Technologies, Inc.	Vendor Devices",
    "2162": "Broadxent (Creative Labs)	Vendor Devices",
    "04ea": "Brooktree Corp.	Vendor Devices",
    "04f9": "Brother Industries, Ltd	Vendor Devices",
    "29e7": "Brunel University	Vendor Devices",
    "25bb": "Brunner Elektronik AG	Vendor Devices",
    "0956": "BSquare Corp.	Vendor Devices",
    "0411": "BUFFALO INC. (formerly MelCo., Inc.)	Vendor Devices",
    "0caf": "Buslink	Vendor Devices",
    "0517": "Butterfly Communications	Vendor Devices",
    "0703": "Bvtech Industry, Inc.	Vendor Devices",
    "19d1": "BYD	Vendor Devices",
    "0a93": "C Technologies AB	Vendor Devices",
    "074c": "C-C-C Group PLC	Vendor Devices",
    "0d8c": "C-Media Electronics, Inc.	Vendor Devices",
    "1032": "C-One Technology Corp.	Vendor Devices",
    "1d17": "C-Thru Music Ltd.	Vendor Devices",
    "0e92": "C's Glory Enterprise Co., Ltd	Vendor Devices",
    "0783": "C3PO	Vendor Devices",
    "0985": "cab Produkttechnik GmbH & Co KG	Vendor Devices",
    "050b": "Cable System International	Vendor Devices",
    "094d": "Cable Television Laboratories	Vendor Devices",
    "10e1": "CablePlus, Ltd	Vendor Devices",
    "10aa": "Cables To Go	Vendor Devices",
    "cace": "CACE Technologies Inc.	Vendor Devices",
    "0b69": "CacheVision	Vendor Devices",
    "0559": "Cadence Design Systems, Inc.	Vendor Devices",
    "27c0": "Cadwell Laboratories, Inc.	Vendor Devices",
    "08fa": "Caere	Vendor Devices",
    "1f28": "Cal-Comp	Vendor Devices",
    "0538": "Caldera International, Inc. (SCO)	Vendor Devices",
    "0dd5": "California Micro Devices	Vendor Devices",
    "22e8": "Cambridge Audio	Vendor Devices",
    "0a12": "Cambridge Silicon Radio, Ltd	Vendor Devices",
    "2cd9": "Cambrionix Ltd	Vendor Devices",
    "0768": "Camtel Technology Corp.	Vendor Devices",
    "29f1": "Canaan Creative Co., Ltd	Vendor Devices",
    "2087": "Cando	Vendor Devices",
    "0a90": "Candy Technology Co., Ltd	Vendor Devices",
    "07bc": "Canon Computer Systems, Inc.	Vendor Devices",
    "2c4f": "Canon Electronic Business Machines Co., Ltd.	Vendor Devices",
    "1083": "Canon Electronics, Inc.	Vendor Devices",
    "1736": "CANON IMAGING SYSTEM TECHNOLOGIES INC.	Vendor Devices",
    "052c": "Canon Information Systems, Inc.	Vendor Devices",
    "04a9": "Canon, Inc.	Vendor Devices",
    "05f0": "Canopus Co., Ltd	Vendor Devices",
    "0491": "Capetronic	Vendor Devices",
    "0498": "Capetronic (Kaohsiung) Corp.	Vendor Devices",
    "c216": "Card Device Expert Co., LTD	Vendor Devices",
    "2685": "Cardo Peripheral Systems LTD	Vendor Devices",
    "0758": "Carl Zeiss Microscopy GmbH	Vendor Devices",
    "07cc": "Carry Computer Eng., Co., Ltd	Vendor Devices",
    "0f0c": "CAS Corp.	Vendor Devices",
    "07cf": "Casio Computer Co., Ltd	Vendor Devices",
    "1967": "CASIO HITACHI Mobile Communications Co., Ltd.	Vendor Devices",
    "0ca6": "Castles Technology Co., Ltd	Vendor Devices",
    "0968": "Catalyst Enterprises, Inc.	Vendor Devices",
    "044c": "CCL/ITRI	Vendor Devices",
    "08ee": "CCSI/Hesso	Vendor Devices",
    "f3f0": "CCT, Inc	Vendor Devices",
    "1065": "CCYU Technology	Vendor Devices",
    "154a": "Celectronic GmbH	Vendor Devices",
    "0cb6": "Celestix Networks, Pte., Ltd	Vendor Devices",
    "19b4": "Celestron	Vendor Devices",
    "1b26": "Cellex Power Products, Inc.	Vendor Devices",
    "0cf5": "Cellink Co., Ltd	Vendor Devices",
    "1733": "Cellink Technology Co., Ltd	Vendor Devices",
    "112f": "Cellon International, Inc.	Vendor Devices",
    "09b5": "Celltrix Technology Co., Ltd	Vendor Devices",
    "211f": "CELOT Corporation	Vendor Devices",
    "0ea8": "CenDyne, Inc.	Vendor Devices",
    "0723": "Centillium Communications Corp.	Vendor Devices",
    "0cf9": "Central System Research Co., Ltd	Vendor Devices",
    "07f7": "Century Corp.	Vendor Devices",
    "0a22": "Century Semiconductor USA, Inc.	Vendor Devices",
    "0796": "Certicom Corp.	Vendor Devices",
    "0c8e": "Cesscom Co., Ltd	Vendor Devices",
    "10f8": "Cesys GmbH	Vendor Devices",
    "068e": "CH Products, Inc.	Vendor Devices",
    "8e06": "CH Products, Inc.	Vendor Devices",
    "24c0": "Chaney Instrument	Vendor Devices",
    "0c62": "Chant Sincere Co., Ltd	Vendor Devices",
    "1b5a": "Chao Zhou Kai Yuan Electric Co., Ltd.	Vendor Devices",
    "073a": "Chaplet Systems, Inc.	Vendor Devices",
    "0d9c": "Chee Chen Hi-Technology Co., Ltd	Vendor Devices",
    "2123": "Cheeky Dream	Vendor Devices",
    "09e9": "Chen-Source, Inc.	Vendor Devices",
    "05c8": "Cheng Uei Precision Industry Co., Ltd (Foxlink)	Vendor Devices",
    "1c49": "Cherng Weei Technology Corp.	Vendor Devices",
    "046a": "Cherry GmbH	Vendor Devices",
    "0a81": "Chesen Electronics Corp.	Vendor Devices",
    "1518": "Cheshire Engineering Corp.	Vendor Devices",
    "0ff7": "CHI SHING Computer Accessories Co., Ltd	Vendor Devices",
    "05fe": "Chic Technology Corp.	Vendor Devices",
    "0472": "Chicony Electronics Co., Ltd	Vendor Devices",
    "04f2": "Chicony Electronics Co., Ltd	Vendor Devices",
    "105f": "Chin Shong Enterprise Co., Ltd	Vendor Devices",
    "1677": "China Huada Integrated Circuit Design (Group) Co., Ltd. (CIDC Group)	Vendor Devices",
    "1a2c": "China Resource Semico Co., Ltd	Vendor Devices",
    "1ba8": "China Telecommunication Technology Labs	Vendor Devices",
    "0e82": "Ching Tai Electric Wire & Cable Co., Ltd	Vendor Devices",
    "11a0": "Chipcon AS	Vendor Devices",
    "1230": "Chipidea-Microelectronica, S.A.	Vendor Devices",
    "0b9f": "Chippo Technologies	Vendor Devices",
    "0420": "Chips and Technologies	Vendor Devices",
    "1e3d": "Chipsbank Microelectronics Co., Ltd	Vendor Devices",
    "0204": "Chipsbank Microelectronics Co., Ltd	Vendor Devices",
    "1976": "Chipsbrand Microelectronics (HK) Co., Ltd.	Vendor Devices",
    "164a": "ChipX	Vendor Devices",
    "108a": "Chloride Power Protection	Vendor Devices",
    "108a": "Chloride Power Protection	Vendor Devices",
    "245f": "Chord Electronics Limited	Vendor Devices",
    "100b": "Chou Chin Industrial Co., Ltd	Vendor Devices",
    "100b": "Chou Chin Industrial Co., Ltd	Vendor Devices",
    "0a69": "Chroma ate, Inc.	Vendor Devices",
    "04ab": "Chromatic Research	Vendor Devices",
    "0639": "Chrontel, Inc.	Vendor Devices",
    "0f31": "Chrysalis Development	Vendor Devices",
    "1044": "Chu Yuen Enterprise Co., Ltd	Vendor Devices",
    "0db4": "Chung Fu Chen Yeh Enterprise Corp.	Vendor Devices",
    "0698": "Chuntex (CTX)	Vendor Devices",
    "050a": "Cinch Connectors	Vendor Devices",
    "07f6": "Circuit Assembly Corp.	Vendor Devices",
    "0488": "Cirque Corp.	Vendor Devices",
    "0429": "Cirrus Logic	Vendor Devices",
    "06d4": "Cisco Systems	Vendor Devices",
    "05a6": "Cisco Systems, Inc.	Vendor Devices",
    "1d90": "Citizen	Vendor Devices",
    "2730": "Citizen	Vendor Devices",
    "1343": "Citizen Systems	Vendor Devices",
    "08bd": "Citizen Watch Co., Ltd	Vendor Devices",
    "09ce": "City Electronics, Ltd	Vendor Devices",
    "0574": "City University of Hong Kong	Vendor Devices",
    "0508": "Clarion Co., Ltd	Vendor Devices",
    "0cf8": "Clarisys, Inc.	Vendor Devices",
    "a88a": "Clas Ohlsson	Vendor Devices",
    "0ffc": "Clavia DMI AB	Vendor Devices",
    "0ffc": "Clavia DMI AB	Vendor Devices",
    "20a0": "Clay Logic	Vendor Devices",
    "0a66": "ClearCube Technology	Vendor Devices",
    "5332": "Clearly Superior Technologies, Inc.	Vendor Devices",
    "1e41": "Cleverscope	Vendor Devices",
    "0d50": "Cleware GmbH	Vendor Devices",
    "166a": "Clipsal	Vendor Devices",
    "ba77": "Clockmaker	Vendor Devices",
    "28f3": "Clover Network, Inc.	Vendor Devices",
    "0003": "Club Mac	Vendor Devices",
    "0453": "CMD Technology	Vendor Devices",
    "7104": "CME (Central Music Co.)	Vendor Devices",
    "16d8": "CMOTECH Co., Ltd.	Vendor Devices",
    "2000": "CMX Systems	Vendor Devices",
    "1f0c": "CMX Systems	Vendor Devices",
    "1371": "CNet Technology Inc.	Vendor Devices",
    "0653": "CNF, Inc.	Vendor Devices",
    "0c8c": "Coactive Networks	Vendor Devices",
    "0d18": "coaXmedia	Vendor Devices",
    "1e74": "Coby Electronics Corporation	Vendor Devices",
    "07c0": "Code Mercenaries Hard- und Software GmbH	Vendor Devices",
    "27bd": "Codethink Ltd.	Vendor Devices",
    "2818": "Codex Digital Limited	Vendor Devices",
    "0d4d": "Coherent, Inc.	Vendor Devices",
    "0959": "Cologne Chip AG	Vendor Devices",
    "0b52": "Colorado MicroDisplay, Inc.	Vendor Devices",
    "085c": "ColorVision, Inc.	Vendor Devices",
    "09d3": "Com One	Vendor Devices",
    "05ec": "COM21, Inc.	Vendor Devices",
    "0a68": "Comaide Corp.	Vendor Devices",
    "1031": "Comax Technology, Inc.	Vendor Devices",
    "0777": "Comda Enterprise Corp.	Vendor Devices",
    "0b51": "Comfort Keyboard Co.	Vendor Devices",
    "0c09": "Comjet Information System	Vendor Devices",
    "1519": "Comneon	Vendor Devices",
    "10b5": "Comodo (PLX?)	Vendor Devices",
    "070d": "Comoss Electronic Co., Ltd	Vendor Devices",
    "04b7": "Compal Electronics, Inc.	Vendor Devices",
    "049f": "Compaq Computer Corp.	Vendor Devices",
    "1183": "Compaq Computer Corp. [hex] (Digital Dream ??)	Vendor Devices",
    "05f1": "Compass Communications	Vendor Devices",
    "1055": "Complex Micro Interconnection Co., Ltd	Vendor Devices",
    "185b": "Compro	Vendor Devices",
    "0cf6": "Compucable Corp.	Vendor Devices",
    "0958": "CompuLink Research, Inc.	Vendor Devices",
    "1516": "CompUSA	Vendor Devices",
    "0423": "Computer Access Technology Corp.	Vendor Devices",
    "0a4c": "Computex Co., Ltd	Vendor Devices",
    "0b73": "Computone Corp.	Vendor Devices",
    "0551": "CompuTrend Systems, Inc.	Vendor Devices",
    "0879": "Comtrol Corp.	Vendor Devices",
    "2fc6": "Comtrue Inc.	Vendor Devices",
    "0ee3": "ComTrue Technology Corp.	Vendor Devices",
    "0c67": "Concept Telecom, Ltd	Vendor Devices",
    "17a4": "Concept2	Vendor Devices",
    "0bb0": "Concord Camera Corp.	Vendor Devices",
    "106e": "ConectL	Vendor Devices",
    "0572": "Conexant Systems (Rockwell), Inc.	Vendor Devices",
    "1af1": "Connect One Ltd.	Vendor Devices",
    "0710": "Connect Tech, Inc.	Vendor Devices",
    "154d": "ConnectCounty Holdings Berhad	Vendor Devices",
    "0478": "Connectix Corp.	Vendor Devices",
    "1aef": "Conntech Electronic (Suzhou) Corporation	Vendor Devices",
    "fc08": "Conrad Electronic SE	Vendor Devices",
    "1bce": "Contac Cable Industrial Limited	Vendor Devices",
    "06ce": "Contec	Vendor Devices",
    "09a4": "Contech Research, Inc.	Vendor Devices",
    "0dd1": "Contek Electronics Co., Ltd	Vendor Devices",
    "0d0b": "Contemporary Controls	Vendor Devices",
    "0b33": "Contour Design, Inc.	Vendor Devices",
    "135f": "Control Development Inc.	Vendor Devices",
    "3036": "Control iD	Vendor Devices",
    "0e5e": "Conwise Technology Co., Ltd.	Vendor Devices",
    "2516": "Cooler Master Co., Ltd.	Vendor Devices",
    "0791": "Copartner Wire and Cable Mfg. Corp.	Vendor Devices",
    "2226": "Copper Mountain technologies	Vendor Devices",
    "0a6f": "Core Technology, Inc.	Vendor Devices",
    "0ff6": "Core Valley Co., Ltd	Vendor Devices",
    "07aa": "Corega K.K.	Vendor Devices",
    "0b5a": "Corel Corp.	Vendor Devices",
    "636c": "CoreLogic, Inc.	Vendor Devices",
    "08f0": "Corex Technologies	Vendor Devices",
    "17eb": "Cornice, Inc.	Vendor Devices",
    "2bd6": "Coroware, Inc.	Vendor Devices",
    "1b1c": "Corsair	Vendor Devices",
    "0610": "Costar Electronics, Inc.	Vendor Devices",
    "15d5": "Coulomb Electronics Ltd.	Vendor Devices",
    "1264": "Covidien Energy-based Devices	Vendor Devices",
    "0e21": "Cowon Systems, Inc.	Vendor Devices",
    "237d": "Cradlepoint	Vendor Devices",
    "041e": "Creative Technology, Ltd	Vendor Devices",
    "1660": "Creatix Polymedia GmbH	Vendor Devices",
    "052a": "Crescent Heart Software	Vendor Devices",
    "0932": "Crescentec Corp.	Vendor Devices",
    "0e1b": "Crewave	Vendor Devices",
    "0544": "Cristie Electronics, Ltd	Vendor Devices",
    "080b": "Cross Match Technologies	Vendor Devices",
    "0feb": "CRS Electronic Co., Ltd	Vendor Devices",
    "0c94": "Cryptera	Vendor Devices",
    "046f": "Crystal Semiconductor	Vendor Devices",
    "0852": "CSEM	Vendor Devices",
    "0d5f": "CSI, Inc.	Vendor Devices",
    "0f08": "CSL Wire & Plug (Shen Zhen) Co.	Vendor Devices",
    "18a4": "CSSN	Vendor Devices",
    "08f1": "CTI Electronics Corp.	Vendor Devices",
    "14ad": "CTK Corporation	Vendor Devices",
    "1136": "CTS Electronincs	Vendor Devices",
    "055e": "CTX Opto-Electronics Corp.	Vendor Devices",
    "1e4e": "Cubeternet	Vendor Devices",
    "0dab": "Cubig Group	Vendor Devices",
    "0afe": "Cummins Engine Co.	Vendor Devices",
    "324c": "CUPRIS Ltd.	Vendor Devices",
    "106c": "Curitel Communications, Inc.	Vendor Devices",
    "1b27": "Current Electronics Inc.	Vendor Devices",
    "049b": "Curtis Computer Products	Vendor Devices",
    "2405": "Custom Computer Services, Inc	Vendor Devices",
    "0dd4": "Custom Engineering SPA	Vendor Devices",
    "0f97": "CviLux Corp.	Vendor Devices",
    "1ff7": "CVT Electronics.Co.,Ltd	Vendor Devices",
    "08a9": "CWAV Inc.	Vendor Devices",
    "0764": "Cyber Power System, Inc.	Vendor Devices",
    "0f98": "CyberBank Corp.	Vendor Devices",
    "0c17": "Cyberboard A/S	Vendor Devices",
    "07d3": "Cyberdata Corp.	Vendor Devices",
    "0c19": "cyberPIXIE, Inc.	Vendor Devices",
    "1142": "CyberScan Technologies, Inc.	Vendor Devices",
    "129b": "CyberTAN Technology	Vendor Devices",
    "0a0b": "Cybex Computer Products Co.	Vendor Devices",
    "0b66": "Cybiko Inc.	Vendor Devices",
    "0665": "Cypress Semiconductor	Vendor Devices",
    "04b4": "Cypress Semiconductor Corp.	Vendor Devices",
    "0633": "Cyrix Corp.	Vendor Devices",
    "05ee": "Cytechinfo Inc.	Vendor Devices",
    "15c9": "D-Box Technologies	Vendor Devices",
    "2001": "D-Link Corp.	Vendor Devices",
    "07d1": "D-Link System	Vendor Devices",
    "0eef": "D-WAV Scientific Co., Ltd	Vendor Devices",
    "041b": "d'TV	Vendor Devices",
    "154e": "D&M Holdings, Inc. (Denon/Marantz)	Vendor Devices",
    "154e": "D&M Holdings, Inc. (Denon/Marantz)	Vendor Devices",
    "06d1": "Daewoo Electronics Co., Ltd	Vendor Devices",
    "04f0": "Daewoo Electronics Co., Ltd	Vendor Devices",
    "04aa": "DaeWoo Telecom, Ltd	Vendor Devices",
    "0d35": "Dah Kun Co., Ltd	Vendor Devices",
    "1452": "Dai Nippon Printing, Inc	Vendor Devices",
    "1dd3": "Dajc Inc.	Vendor Devices",
    "04fa": "Dallas Semiconductor	Vendor Devices",
    "1970": "Dane-Elec Corp. USA	Vendor Devices",
    "0da0": "Danger Research	Vendor Devices",
    "2002": "DAP Technologies	Vendor Devices",
    "0d62": "Darfon Electronics Corp.	Vendor Devices",
    "03ea": "Data Broadcasting Corp.	Vendor Devices",
    "1aa4": "Data Drive Thru, Inc.	Vendor Devices",
    "0ada": "Data Encryption Systems Ltd.	Vendor Devices",
    "19b9": "Data Robotics	Vendor Devices",
    "0826": "Data Transit	Vendor Devices",
    "0867": "Data Translation, Inc.	Vendor Devices",
    "09a7": "Data Transmission Network Corp.	Vendor Devices",
    "0a27": "Datacard Group	Vendor Devices",
    "07c4": "Datafab Systems, Inc.	Vendor Devices",
    "0974": "Datagraphix, a business unit of Anacomp	Vendor Devices",
    "080c": "Datalogic S.p.A.	Vendor Devices",
    "0b0b": "Datamax-O'Neil	Vendor Devices",
    "1228": "Datapaq Limited	Vendor Devices",
    "0fc6": "Dataplus Supplies, Inc.	Vendor Devices",
    "1c78": "Datascope Corp.	Vendor Devices",
    "109a": "DATASOFT Systems GmbH	Vendor Devices",
    "1c1a": "Datel Electronics Ltd.	Vendor Devices",
    "0ddd": "Datelink Technology Co., Ltd	Vendor Devices",
    "0a46": "Davicom Semiconductor, Inc.	Vendor Devices",
    "07df": "David Electronics Co., Ltd	Vendor Devices",
    "07d0": "Dazzle	Vendor Devices",
    "056b": "Decicon, Inc.	Vendor Devices",
    "2fad": "Definium Technologies	Vendor Devices",
    "1297": "DekTec	Vendor Devices",
    "0fc5": "Delcom Engineering	Vendor Devices",
    "105d": "Delkin Devices, Inc.	Vendor Devices",
    "047c": "Dell Computer Corp.	Vendor Devices",
    "413c": "Dell Computer Corp.	Vendor Devices",
    "1685": "Delock	Vendor Devices",
    "1163": "DeLorme Publishing, Inc.	Vendor Devices",
    "1fbd": "Delphin Technology AG	Vendor Devices",
    "05dd": "Delta Electronics, Inc.	Vendor Devices",
    "1436": "Denali Software, Inc.	Vendor Devices",
    "0580": "Denron, Inc.	Vendor Devices",
    "1014": "Densitron Technologies PLC	Vendor Devices",
    "076d": "Denso Corp.	Vendor Devices",
    "23b4": "Dental Wings Inc.	Vendor Devices",
    "1233": "Denver Electronics	Vendor Devices",
    "0c38": "Der An Electric Wire & Cable Co., Ltd	Vendor Devices",
    "1fba": "DERMALOG Identification Systems GmbH	Vendor Devices",
    "1ad1": "Desay Wire Co., Ltd.	Vendor Devices",
    "2003": "detectomat	Vendor Devices",
    "086c": "DeTeWe - Deutsche Telephonwerke AG & Co.	Vendor Devices",
    "0c78": "Detto Corp.	Vendor Devices",
    "2018": "Deutsche Telekom AG	Vendor Devices",
    "0aa4": "Develco Elektronik	Vendor Devices",
    "28d4": "Devialet	Vendor Devices",
    "1039": "devolo AG	Vendor Devices",
    "1d19": "Dexatek Technology Ltd.	Vendor Devices",
    "12cf": "DEXIN	Vendor Devices",
    "05f2": "Dexin Corp., Ltd	Vendor Devices",
    "0f73": "DFI	Vendor Devices",
    "0450": "DFI, Inc.	Vendor Devices",
    "2a88": "DFU Technology Ltd	Vendor Devices",
    "2dcf": "Dialog Semiconductor	Vendor Devices",
    "05b5": "Dialogic Corp.	Vendor Devices",
    "14e1": "Dialogue Technology Corp.	Vendor Devices",
    "07de": "Diamond Multimedia	Vendor Devices",
    "0a5d": "Diatrend Corp.	Vendor Devices",
    "10b8": "DiBcom	Vendor Devices",
    "0554": "Dictaphone Corp.	Vendor Devices",
    "03f4": "Diebold, Inc.	Vendor Devices",
    "134e": "Digby's Bitpile, Inc. DBA D Bit	Vendor Devices",
    "04d0": "Digi International	Vendor Devices",
    "05c5": "Digi International, Inc.	Vendor Devices",
    "08fd": "Digianswer A/S	Vendor Devices",
    "07a1": "Digicom S.p.A.	Vendor Devices",
    "0dba": "Digidesign	Vendor Devices",
    "0dba": "Digidesign	Vendor Devices",
    "1443": "Digilent	Vendor Devices",
    "2375": "Digit@lway, Inc.	Vendor Devices",
    "04a0": "Digital Equipment Corp.	Vendor Devices",
    "074e": "Digital Stream Corp.	Vendor Devices",
    "0eee": "Digital Stream Technology, Inc.	Vendor Devices",
    "0513": "digital-X, Inc.	Vendor Devices",
    "05ba": "DigitalPersona, Inc.	Vendor Devices",
    "2735": "DigitalWay	Vendor Devices",
    "0aaf": "Digitalway Co., Ltd	Vendor Devices",
    "1210": "DigiTech	Vendor Devices",
    "161c": "Digitech Systems	Vendor Devices",
    "268b": "Dimension Engineering	Vendor Devices",
    "10bc": "Dinging Technology Co., Ltd	Vendor Devices",
    "0892": "DioGraphy, Inc.	Vendor Devices",
    "0abf": "Diolan	Vendor Devices",
    "0f69": "Dionex Corp.	Vendor Devices",
    "1d1f": "Diostech Co., Ltd.	Vendor Devices",
    "0b9b": "Dipl.-Ing. Stefan Kunde	Vendor Devices",
    "0fd5": "Direct Access Technology, Inc.	Vendor Devices",
    "0829": "DirecTV Broadband, Inc. (Telocity)	Vendor Devices",
    "226e": "DISPLAX	Vendor Devices",
    "17e9": "DisplayLink	Vendor Devices",
    "3579": "DIVA	Vendor Devices",
    "06a5": "Divio	Vendor Devices",
    "2ca3": "DJI Technology Co., Ltd.	Vendor Devices",
    "0afa": "DMC Co., Ltd.	Vendor Devices",
    "2a03": "dog hunter AG	Vendor Devices",
    "0d87": "Dolby Laboratories Inc.	Vendor Devices",
    "2c1a": "Dolphin Peripherals	Vendor Devices",
    "071b": "Domain Technologies, Inc.	Vendor Devices",
    "0be5": "DOME imaging systems, Inc.	Vendor Devices",
    "0ccc": "Domex Technology Corp.	Vendor Devices",
    "0be6": "Dong Guan Humen Wonderful Wire Cable Factory	Vendor Devices",
    "0c59": "Dong Guan Shinko Wire Co., Ltd	Vendor Devices",
    "16ac": "Dongguan ChingLung Wire & Cable Co., Ltd.	Vendor Devices",
    "1b86": "Dongguan Guanshang Electronics Co., Ltd.	Vendor Devices",
    "1975": "Dongguan Guneetal Wire & Cable Co., Ltd.	Vendor Devices",
    "0f53": "Dongguan White Horse Cable Factory, Ltd	Vendor Devices",
    "04ad": "Dooin Electronics	Vendor Devices",
    "8ea3": "Doosl	Vendor Devices",
    "07f9": "Dotop Technology, Inc.	Vendor Devices",
    "07eb": "Double-H Technology Co., Ltd	Vendor Devices",
    "0f7c": "DQ Technology, Inc.	Vendor Devices",
    "289b": "Dracal/Raphnet technologies	Vendor Devices",
    "0079": "DragonRise Inc.	Vendor Devices",
    "0675": "DrayTek Corp.	Vendor Devices",
    "07fa": "DrayTek Corp.	Vendor Devices",
    "1d34": "Dream Cheeky	Vendor Devices",
    "1941": "Dream Link	Vendor Devices",
    "1cf1": "Dresden Elektronik	Vendor Devices",
    "1395": "DSEA A/S	Vendor Devices",
    "0ef4": "DSI Datotech	Vendor Devices",
    "1487": "DSP Group, Ltd.	Vendor Devices",
    "0b50": "Dumpries Co., Ltd	Vendor Devices",
    "0c0b": "Dura Micro, Inc. (Acomdata)	Vendor Devices",
    "0449": "Duta Multi Robotik	Vendor Devices",
    "0fe9": "DVICO	Vendor Devices",
    "0d64": "DXG Technology Corp.	Vendor Devices",
    "fa11": "DyingLight	Vendor Devices",
    "0922": "Dymo-CoStar Corp.	Vendor Devices",
    "1a89": "Dynalith Systems Co., Ltd.	Vendor Devices",
    "12f5": "Dynamic System Electronics Corp.	Vendor Devices",
    "0650": "Dynapro Systems	Vendor Devices",
    "0fcf": "Dynastream Innovations, Inc.	Vendor Devices",
    "19ff": "Dynex	Vendor Devices",
    "0c36": "E Ink Corp.	Vendor Devices",
    "04ff": "E-CMOS Corp.	Vendor Devices",
    "2560": "e-con Systems	Vendor Devices",
    "0cf1": "e-Conn Electronic Co., Ltd	Vendor Devices",
    "0edf": "e-MDT Co., Ltd	Vendor Devices",
    "1b8d": "e-MOVE Technology Co., Ltd.	Vendor Devices",
    "0c37": "e.Digital	Vendor Devices",
    "12b9": "E28	Vendor Devices",
    "18b4": "e3C Technologies	Vendor Devices",
    "08a5": "e9, Inc.	Vendor Devices",
    "232e": "EA Elektro-Automatik GmbH & Co. KG	Vendor Devices",
    "0d4f": "EADS Airbus France	Vendor Devices",
    "1ef6": "EADS Deutschland GmbH	Vendor Devices",
    "3125": "Eagletron	Vendor Devices",
    "0c35": "Eagletron, Inc.	Vendor Devices",
    "0ffd": "EarlySense	Vendor Devices",
    "0a5b": "EAsics NV	Vendor Devices",
    "1060": "Easthome Industrial Co., Ltd	Vendor Devices",
    "1101": "EasyPass Industrial Co., Ltd	Vendor Devices",
    "18cd": "Ecamm	Vendor Devices",
    "0920": "Echelon Co.	Vendor Devices",
    "040f": "Echo Speech Corp.	Vendor Devices",
    "0bc9": "ECI Telecom, Ltd	Vendor Devices",
    "06bb": "EDA, Inc.	Vendor Devices",
    "7392": "Edimax Technology Co., Ltd	Vendor Devices",
    "1ce0": "EDIMAX TECHNOLOGY CO., LTD.	Vendor Devices",
    "09f7": "Edu-Science (H.K.), Ltd	Vendor Devices",
    "060c": "EEH Datalink GmbH	Vendor Devices",
    "067c": "Efficient Networks, Inc.	Vendor Devices",
    "1aa6": "eFortune Technology Corp.	Vendor Devices",
    "8341": "EGO Systems, Inc.	Vendor Devices",
    "0a92": "EGO SYStems, Inc.	Vendor Devices",
    "071d": "Eicon Networks Corp.	Vendor Devices",
    "048f": "Eicon Tech.	Vendor Devices",
    "0bb9": "Eiger M&C Co., Ltd	Vendor Devices",
    "056d": "EIZO Corp.	Vendor Devices",
    "0440": "Eizo Nanao Corp.	Vendor Devices",
    "04f3": "Elan Microelectronics Corp.	Vendor Devices",
    "0d10": "Elastic Networks	Vendor Devices",
    "09d8": "ELATEC GmbH	Vendor Devices",
    "0db7": "ELCON Systemtechnik	Vendor Devices",
    "0db7": "ELCON Systemtechnik	Vendor Devices",
    "056e": "Elecom Co., Ltd	Vendor Devices",
    "26b5": "Electrocompaniet	Vendor Devices",
    "21a4": "Electronic Arts Inc.	Vendor Devices",
    "0b1e": "Electronic Warfare Assoc., Inc. (EWA)	Vendor Devices",
    "0a5a": "Electronics For Imaging, Inc.	Vendor Devices",
    "2650": "Electronics For Imaging, Inc. [hex]	Vendor Devices",
    "09cf": "Electronics Testing Center, Taiwan	Vendor Devices",
    "05e2": "ElecVision, Inc.	Vendor Devices",
    "25bf": "Elegant Invention	Vendor Devices",
    "07cd": "Elektor	Vendor Devices",
    "1935": "Elektron Music Machines	Vendor Devices",
    "0fd9": "Elgato Systems GmbH	Vendor Devices",
    "2fe7": "ELGIN S.A.	Vendor Devices",
    "0819": "eLicenser	Vendor Devices",
    "03fc": "Elitegroup Computer Systems	Vendor Devices",
    "1019": "Elitegroup Computer Systems (ECS)	Vendor Devices",
    "0be4": "Elka International, Ltd	Vendor Devices",
    "0b85": "Elkat Electronics, Sdn., Bhd.	Vendor Devices",
    "1500": "Ellisys	Vendor Devices",
    "0aba": "Ellisys	Vendor Devices",
    "0c40": "ELMCU	Vendor Devices",
    "07e2": "Elmeg GmbH & Co., Ltd	Vendor Devices",
    "04e7": "Elo TouchSystems	Vendor Devices",
    "0577": "ELSA	Vendor Devices",
    "05cc": "ELSA AG	Vendor Devices",
    "1484": "Elsa AG [hex]	Vendor Devices",
    "1c29": "Elster GmbH	Vendor Devices",
    "18ef": "ELV Elektronik AG	Vendor Devices",
    "0e93": "eM Technics Co., Ltd	Vendor Devices",
    "086a": "Emagic Soft- und Hardware GmbH	Vendor Devices",
    "0b72": "Embedded Wireless Technology Co., Ltd	Vendor Devices",
    "1ba4": "Ember Corporation	Vendor Devices",
    "06f2": "Emine Technology Co.	Vendor Devices",
    "0c65": "Eminence Enterprise Co., Ltd	Vendor Devices",
    "21a1": "Emotiv Systems Pty. Ltd.	Vendor Devices",
    "084f": "Empeg	Vendor Devices",
    "eb1a": "eMPIA Technology, Inc.	Vendor Devices",
    "12d6": "EMS Dr. Thomas Wuensche	Vendor Devices",
    "4670": "EMS Production	Vendor Devices",
    "0cc4": "emsys GmbH	Vendor Devices",
    "6557": "Emtec	Vendor Devices",
    "2a4b": "EMULEX Corporation	Vendor Devices",
    "1009": "Emuzed, Inc.	Vendor Devices",
    "203d": "Encore Electronics Inc.	Vendor Devices",
    "0eb7": "Endor AG	Vendor Devices",
    "03e8": "EndPoints, Inc.	Vendor Devices",
    "1524": "ENE Technology Inc	Vendor Devices",
    "0cf2": "ENE Technology, Inc.	Vendor Devices",
    "1756": "ENENSYS Technologies	Vendor Devices",
    "1b47": "Energizer Holdings, Inc.	Vendor Devices",
    "0f0e": "Energy Full Corp.	Vendor Devices",
    "2544": "Energy Micro AS	Vendor Devices",
    "1274": "Ensoniq	Vendor Devices",
    "1645": "Entrega [hex]	Vendor Devices",
    "066d": "Entrega, Inc.	Vendor Devices",
    "132a": "Envara Inc.	Vendor Devices",
    "132a": "Envara Inc.	Vendor Devices",
    "5555": "Epiphan Systems Inc.	Vendor Devices",
    "0fa7": "Epox Computer Co., Ltd	Vendor Devices",
    "0570": "Epson America	Vendor Devices",
    "03f8": "Epson Imaging Technology Center	Vendor Devices",
    "1b1f": "eQ-3 Entwicklung GmbH	Vendor Devices",
    "10cb": "Eratech	Vendor Devices",
    "042a": "Ericsson Austrian, AG	Vendor Devices",
    "0bdb": "Ericsson Business Mobile Networks BV	Vendor Devices",
    "0442": "Ericsson, Inc.	Vendor Devices",
    "08ea": "Ericsson, Inc., Blue Ridge Labs	Vendor Devices",
    "2573": "ESI Audiotechnik GmbH	Vendor Devices",
    "109f": "eSOL Co., Ltd	Vendor Devices",
    "0495": "ESS Technology, Inc.	Vendor Devices",
    "0d7f": "Essential Reality LLC	Vendor Devices",
    "0664": "ET&T Technology Co., Ltd.	Vendor Devices",
    "056c": "eTEK Labs	Vendor Devices",
    "102c": "Etoms Electronics Corp.	Vendor Devices",
    "2500": "Ettus Research LLC	Vendor Devices",
    "22b9": "eTurboTouch Technology, Inc.	Vendor Devices",
    "073d": "Eutron S.p.a.	Vendor Devices",
    "148e": "EVATRONIX SA	Vendor Devices",
    "1b12": "Eventide	Vendor Devices",
    "0749": "EVer Electronics Corp.	Vendor Devices",
    "1147": "Ever Great Electric Wire and Cable Co., Ltd	Vendor Devices",
    "080a": "Evermuch Technology Co., Ltd	Vendor Devices",
    "1897": "Evertop Wire Cable Co.	Vendor Devices",
    "0f49": "Evolis SA	Vendor Devices",
    "2d81": "Evollve Inc.	Vendor Devices",
    "1a7c": "Evoluent	Vendor Devices",
    "0a4d": "Evolution Electronics, Ltd	Vendor Devices",
    "04e2": "Exar Corp.	Vendor Devices",
    "070e": "Excel Cell Electronic Co., Ltd	Vendor Devices",
    "11ab": "Exito Electronics Co., Ltd	Vendor Devices",
    "0b65": "Expert Magnetics Corp.	Vendor Devices",
    "0b86": "Exputer Systems, Inc.	Vendor Devices",
    "08e9": "Extended Systems, Inc.	Vendor Devices",
    "1456": "Extending Wire & Cable Co., Ltd.	Vendor Devices",
    "1bf5": "Extranet Systems Inc.	Vendor Devices",
    "0bc6": "ExWAY, Inc.	Vendor Devices",
    "0518": "EzKEY Corp.	Vendor Devices",
    "1c40": "EZPrototypes	Vendor Devices",
    "2256": "Faderfox	Vendor Devices",
    "0b67": "Fairbanks Scales	Vendor Devices",
    "2ae5": "Fairphone B.V.	Vendor Devices",
    "3767": "Fanatec	Vendor Devices",
    "0906": "Faraday Technology Corp.	Vendor Devices",
    "03fe": "Farallon Comunications	Vendor Devices",
    "09b0": "Fargo	Vendor Devices",
    "12ff": "Fascinating Electronics, Inc.	Vendor Devices",
    "0850": "Fast Point Technologies, Inc.	Vendor Devices",
    "0514": "FCI Electronics	Vendor Devices",
    "1702": "FDI-MATELEC	Vendor Devices",
    "1934": "Feature Integration Technology Inc. (Fintek)	Vendor Devices",
    "0ab1": "FEIG ELECTRONIC GmbH	Vendor Devices",
    "096e": "Feitian Technologies, Inc.	Vendor Devices",
    "09dd": "Fellowes, Inc.	Vendor Devices",
    "1ed8": "FENDER MUSICAL INSTRUMENTS CORPORATION	Vendor Devices",
    "0d0f": "Feng Shin Cable Co., Ltd	Vendor Devices",
    "1e29": "Festo AG & Co. KG	Vendor Devices",
    "05eb": "FFC, Ltd	Vendor Devices",
    "0ed5": "Fiberbyte	Vendor Devices",
    "1582": "Fiberline	Vendor Devices",
    "2125": "Fiberpro Inc.	Vendor Devices",
    "2cb7": "Fibocom	Vendor Devices",
    "1508": "Fibocom	Vendor Devices",
    "2972": "FiiO Electronics Technology	Vendor Devices",
    "0863": "Filanet Corp.	Vendor Devices",
    "18fd": "FineArch Inc.	Vendor Devices",
    "0f18": "Finger Lakes Instrumentation	Vendor Devices",
    "0e97": "Fingerworks, Inc.	Vendor Devices",
    "1cd5": "Firecomms Ltd.	Vendor Devices",
    "0c00": "FireFly Mouse Mat	Vendor Devices",
    "04a2": "FirePower Systems	Vendor Devices",
    "0dc7": "First Cable Line, Inc.	Vendor Devices",
    "05b1": "First International Computer, Inc.	Vendor Devices",
    "1509": "First International Computer, Inc.	Vendor Devices",
    "1457": "First International Computer, Inc.	Vendor Devices",
    "0aa5": "First International Digital	Vendor Devices",
    "2765": "Firstbeat Technologies, Ltd.	Vendor Devices",
    "2687": "Fitbit Inc.	Vendor Devices",
    "2687": "Fitbit Inc.	Vendor Devices",
    "0d3e": "Fitcom, inc.	Vendor Devices",
    "18e3": "Fitipower Integrated Technology Inc	Vendor Devices",
    "1923": "FitLinxx	Vendor Devices",
    "0585": "FlashPoint Technology, Inc.	Vendor Devices",
    "25b5": "FlatFrog	Vendor Devices",
    "0f24": "Flex-P Industries, Snd., Bhd.	Vendor Devices",
    "1cfd": "Flextronics Digital Design Japan, LTD.	Vendor Devices",
    "09cb": "FLIR Systems	Vendor Devices",
    "0f7e": "Fluke Corp.	Vendor Devices",
    "0cb0": "Flying Pig Systems	Vendor Devices",
    "2a62": "Flymaster Avionics	Vendor Devices",
    "1306": "FM20 Barcode Scanner	Vendor Devices",
    "ffee": "FNK Tech	Vendor Devices",
    "1235": "Focusrite-Novation	Vendor Devices",
    "0cf4": "Fomtex Corp.	Vendor Devices",
    "063d": "Fong Kai Industrial Co., Ltd	Vendor Devices",
    "1451": "Force Dimension	Vendor Devices",
    "1bc4": "Ford Motor Co.	Vendor Devices",
    "147a": "Formosa Industrial Computing, Inc.	Vendor Devices",
    "1cbf": "FORTAT SKYMARK INDUSTRIAL COMPANY	Vendor Devices",
    "04d5": "Forte Technologies, Inc.	Vendor Devices",
    "22a7": "Fortinet Technologies	Vendor Devices",
    "077c": "Forward Electronics Co., Ltd	Vendor Devices",
    "0e67": "Fossil, Inc.	Vendor Devices",
    "05b0": "Fountain Technologies, Inc.	Vendor Devices",
    "0489": "Foxconn / Hon Hai	Vendor Devices",
    "105b": "Foxconn International, Inc.	Vendor Devices",
    "06dc": "Foxlink Image Technology Co., Ltd	Vendor Devices",
    "2466": "Fractal Audio Systems	Vendor Devices",
    "0437": "Framatome Connectors USA	Vendor Devices",
    "09b2": "Franklin Electronic Publishers, Inc.	Vendor Devices",
    "1fac": "Franklin Wireless	Vendor Devices",
    "234b": "Free Software Initiative of Japan	Vendor Devices",
    "07ab": "Freecom Technologies	Vendor Devices",
    "0f4e": "Freedom Scientific	Vendor Devices",
    "15a2": "Freescale Semiconductor, Inc.	Vendor Devices",
    "1d5c": "Fresco Logic	Vendor Devices",
    "1b73": "Fresco Logic	Vendor Devices",
    "0d63": "Fritz Gegauf AG	Vendor Devices",
    "165b": "Frontier Design Group	Vendor Devices",
    "16d3": "Frontline Test Equipment, Inc.	Vendor Devices",
    "0001": "Fry's Electronics	Vendor Devices",
    "05e5": "Fuji Electric Co., Ltd	Vendor Devices",
    "1c20": "Fuji Electric Device Technology Co., Ltd.	Vendor Devices",
    "05a2": "Fuji Film Microdevices Co., Ltd	Vendor Devices",
    "04cb": "Fuji Photo Film Co., Ltd	Vendor Devices",
    "0550": "Fuji Xerox Co., Ltd	Vendor Devices",
    "1eab": "Fujian Newland Computer Co., Ltd	Vendor Devices",
    "0501": "Fujikura DDK, Ltd	Vendor Devices",
    "0430": "Fujitsu Component Limited	Vendor Devices",
    "087e": "Fujitsu Computer Products of America	Vendor Devices",
    "30ee": "Fujitsu Connected Technologies Limited	Vendor Devices",
    "090f": "Fujitsu Devices, Inc.	Vendor Devices",
    "06ac": "Fujitsu Laboratories of America, Inc.	Vendor Devices",
    "0a4b": "Fujitsu Media Devices, Ltd	Vendor Devices",
    "054a": "Fujitsu Microelectronics, Inc.	Vendor Devices",
    "0407": "Fujitsu Personal Systems, Inc.	Vendor Devices",
    "0bf8": "Fujitsu Siemens Computers	Vendor Devices",
    "08d4": "Fujitsu Siemens Computers	Vendor Devices",
    "0406": "Fujitsu-ICL Computers	Vendor Devices",
    "04f5": "Fujitsu-ICL Systems, Inc.	Vendor Devices",
    "04c5": "Fujitsu, Ltd	Vendor Devices",
    "2fb2": "Fujitsu, Ltd	Vendor Devices",
    "1010": "Fukuda Denshi Co., Ltd	Vendor Devices",
    "0d42": "Full Der Co., Ltd	Vendor Devices",
    "0def": "Full Rise Electronic Co., Ltd	Vendor Devices",
    "0f1c": "Funai Electric Co., Ltd	Vendor Devices",
    "1404": "Fundamental Software, Inc.	Vendor Devices",
    "0c3a": "Furui Precise Component (Kunshan) Co., Ltd	Vendor Devices",
    "1b71": "Fushicai	Vendor Devices",
    "1491": "Futronic Technology Co. Ltd.	Vendor Devices",
    "19c2": "Futuba	Vendor Devices",
    "0616": "Future Techno Designs PVT, Ltd	Vendor Devices",
    "0e95": "Future Technology Co., Ltd	Vendor Devices",
    "0403": "Future Technology Devices International, Ltd	Vendor Devices",
    "16f5": "Futurelogic Inc.	Vendor Devices",
    "04f8": "FuturePlus Systems	Vendor Devices",
    "0bc1": "Fuw Yng Electronics Co., Ltd	Vendor Devices",
    "2207": "Fuzhou Rockchip Electronics Company	Vendor Devices",
    "1f4d": "G-Tek Electronics Group	Vendor Devices",
    "0dc0": "G7 Solutions (formerly Great Notions)	Vendor Devices",
    "09ff": "Gain Technology Corp.	Vendor Devices",
    "06fe": "Gallant Computer, Inc.	Vendor Devices",
    "19fa": "Gampaq Co.Ltd	Vendor Devices",
    "049a": "Gandalf Technologies, Ltd	Vendor Devices",
    "091e": "Garmin International	Vendor Devices",
    "107b": "Gateway, Inc.	Vendor Devices",
    "0443": "Gateway, Inc.	Vendor Devices",
    "10cc": "GBM Connector Co., Ltd	Vendor Devices",
    "0825": "GC Protronics	Vendor Devices",
    "07d7": "GCC Technologies, Inc.	Vendor Devices",
    "1076": "GCT Semiconductor, Inc.	Vendor Devices",
    "28e9": "GDMicroelectronics	Vendor Devices",
    "1901": "GE Healthcare	Vendor Devices",
    "05d0": "GE Medical Systems Lunar	Vendor Devices",
    "0b38": "Gear Head	Vendor Devices",
    "15aa": "Gearway Electronics (Dong Guan) Co., Ltd.	Vendor Devices",
    "08e6": "Gemalto (was Gemplus)	Vendor Devices",
    "1e2d": "Gemalto M2M GmbH	Vendor Devices",
    "1908": "GEMBIRD	Vendor Devices",
    "12bd": "Gembird	Vendor Devices",
    "23c7": "Gemini	Vendor Devices",
    "14c2": "Gemlight Computer, Ltd	Vendor Devices",
    "0993": "Gemstar eBook Group, Ltd	Vendor Devices",
    "15a9": "Gemtek	Vendor Devices",
    "1743": "General Atomics	Vendor Devices",
    "1b1e": "General Imaging / General Electric	Vendor Devices",
    "0bbb": "General Meters Corp.	Vendor Devices",
    "1b3f": "Generalplus Technology Inc.	Vendor Devices",
    "0dfc": "GeneralTouch Technology Co., Ltd	Vendor Devices",
    "1209": "Generic	Vendor Devices",
    "05e3": "Genesys Logic, Inc.	Vendor Devices",
    "0f2e": "Geniality Maple Technology Co., Ltd	Vendor Devices",
    "0809": "Genicom Technology, Inc.	Vendor Devices",
    "03f1": "Genoa Technology	Vendor Devices",
    "09c0": "Genpix Electronics, LLC	Vendor Devices",
    "0608": "Genrad Ads	Vendor Devices",
    "9148": "GeoLab, Ltd	Vendor Devices",
    "1c4b": "Geratherm Medical AG	Vendor Devices",
    "1753": "GERTEC Telecomunicacoes Ltda.	Vendor Devices",
    "0e0c": "Gesytec	Vendor Devices",
    "0fd1": "Giant Electronics Ltd.	Vendor Devices",
    "1059": "Giesecke & Devrient GmbH	Vendor Devices",
    "0414": "Giga-Byte Technology Co., Ltd	Vendor Devices",
    "1667": "GIGA-TMS INC.	Vendor Devices",
    "116e": "Gigastorage Corp.	Vendor Devices",
    "0a39": "Gilat Satellite Networks, Ltd	Vendor Devices",
    "0cc1": "Given Imaging, Ltd	Vendor Devices",
    "16ab": "Global Sun Technology	Vendor Devices",
    "0d8e": "Global Sun Technology, Inc.	Vendor Devices",
    "1a6e": "Global Unichip Corp.	Vendor Devices",
    "083f": "Global Village	Vendor Devices",
    "053b": "Global Village Communication	Vendor Devices",
    "11aa": "GlobalMedia Group, LLC	Vendor Devices",
    "0915": "GlobeSpan, Inc.	Vendor Devices",
    "0a91": "Globlink Technology, Inc.	Vendor Devices",
    "0656": "Glory Mark Electronic, Ltd	Vendor Devices",
    "0c54": "Glory, Ltd	Vendor Devices",
    "0e7e": "Gmate, Inc.	Vendor Devices",
    "16f0": "GN Hearing A/S	Vendor Devices",
    "0b0e": "GN Netcom	Vendor Devices",
    "1684": "Godspeed Computer Corp.	Vendor Devices",
    "09f3": "GoFlight, Inc.	Vendor Devices",
    "0921": "GoHubs, Inc.	Vendor Devices",
    "1680": "Golden Bridge Electech Inc.	Vendor Devices",
    "0690": "Golden Bridge Electech, Inc.	Vendor Devices",
    "0732": "Goldfull Electronics & Telecommunications Corp.	Vendor Devices",
    "1c1f": "Goldvish S.A.	Vendor Devices",
    "1631": "Good Way Technology	Vendor Devices",
    "065f": "Good Way Technology Co., Ltd & GWC technology Inc.	Vendor Devices",
    "18d1": "Google Inc.	Vendor Devices",
    "4255": "GoPro	Vendor Devices",
    "2672": "GoPro	Vendor Devices",
    "08f2": "Gotop Information Inc.	Vendor Devices",
    "5654": "Gotview	Vendor Devices",
    "2a13": "Grabba International	Vendor Devices",
    "108b": "Grand-tek Technology Co., Ltd	Vendor Devices",
    "99fa": "Grandtec	Vendor Devices",
    "5032": "Grandtec	Vendor Devices",
    "0797": "Grandtech Semiconductor Corp.	Vendor Devices",
    "0654": "Granite Microsystems, Inc.	Vendor Devices",
    "0d4b": "Grape Systems, Inc.	Vendor Devices",
    "0b4d": "Graphtec America, Inc.	Vendor Devices",
    "0bfb": "Grass Valley Group	Vendor Devices",
    "06ad": "Greatland Electronics Taiwan, Ltd	Vendor Devices",
    "062b": "Greatlink Electronics Taiwan, Ltd	Vendor Devices",
    "0b5f": "Green Electronics Co., Ltd	Vendor Devices",
    "0e1e": "Green Hills Software	Vendor Devices",
    "0e1e": "Green Hills Software	Vendor Devices",
    "0a6b": "Green House Co., Ltd	Vendor Devices",
    "0e8f": "GreenAsia Inc.	Vendor Devices",
    "0fe5": "Greenconn (U.S.A.), Inc.	Vendor Devices",
    "0971": "Gretag-Macbeth AG	Vendor Devices",
    "05bb": "Grey Cell Systems	Vendor Devices",
    "17b3": "Grey Innovation	Vendor Devices",
    "077d": "Griffin Technology	Vendor Devices",
    "09bc": "Grundig	Vendor Devices",
    "0ec5": "GT Information System Co., Ltd	Vendor Devices",
    "078c": "GTCO/CalComp	Vendor Devices",
    "13d7": "Guidance Software, Inc.	Vendor Devices",
    "06f8": "Guillemot Corp.	Vendor Devices",
    "0f78": "Guntermann & Drunck GmbH	Vendor Devices",
    "0579": "GVC Corp.	Vendor Devices",
    "4757": "GW Instek	Vendor Devices",
    "2184": "GW Instek	Vendor Devices",
    "1831": "Gwo Jinn Industries Co., Ltd.	Vendor Devices",
    "0c16": "Gyration, Inc.	Vendor Devices",
    "1852": "GYROCOM C&C Co., LTD	Vendor Devices",
    "1f48": "H-TRONIC GmbH	Vendor Devices",
    "0d80": "H.R. Silvine Electronics, Inc.	Vendor Devices",
    "06c5": "Hagenuk, GmbH	Vendor Devices",
    "0693": "Hagiwara Sys-Com Co., Ltd	Vendor Devices",
    "201e": "Haier	Vendor Devices",
    "a466": "Haikou Xingong Electronics Co.,Ltd	Vendor Devices",
    "0b41": "Hal Corp.	Vendor Devices",
    "f766": "Hama	Vendor Devices",
    "147f": "Hama GmbH & Co., KG	Vendor Devices",
    "0af9": "Hama, Inc.	Vendor Devices",
    "0661": "Hamamatsu Photonics K.K.	Vendor Devices",
    "1d0b": "HAN HUA CABLE & WIRE TECHNOLOGY (J.X.) CO., LTD.	Vendor Devices",
    "0536": "Hand Held Products (Welch Allyn, Inc.)	Vendor Devices",
    "082d": "Handspring	Vendor Devices",
    "15f4": "HanfTek	Vendor Devices",
    "0c1c": "Hang Zhou Silan Electronics Co., Ltd	Vendor Devices",
    "1bd0": "Hangzhou Riyue Electronic Co., Ltd.	Vendor Devices",
    "0218": "Hangzhou Worlde	Vendor Devices",
    "2cc0": "Hangzhou Zero Zero Infinity Technology Co., Ltd.	Vendor Devices",
    "0d19": "Hank Connection Industrial Co., Ltd	Vendor Devices",
    "0887": "Hannstar Electronics Corp.	Vendor Devices",
    "0d12": "Hansol Electronics, Inc.	Vendor Devices",
    "20b3": "Hanvon	Vendor Devices",
    "0c9a": "Hanwool Robotics Corp.	Vendor Devices",
    "078b": "Happ Controls, Inc.	Vendor Devices",
    "8301": "Hapurs	Vendor Devices",
    "05fc": "Harman	Vendor Devices",
    "0931": "Harmonic Data Systems, Ltd	Vendor Devices",
    "1bad": "Harmonix Music	Vendor Devices",
    "19a5": "HARRIS Corp.	Vendor Devices",
    "04f4": "Harting Elektronik, Inc.	Vendor Devices",
    "06af": "Harting, Inc. of North America	Vendor Devices",
    "0c06": "Hasbro Games, Inc.	Vendor Devices",
    "2e0e": "Hatteland Display AS	Vendor Devices",
    "2040": "Hauppauge	Vendor Devices",
    "0fb0": "Haurtian Wire & Cable Co., Ltd	Vendor Devices",
    "0e66": "Hawking Technologies	Vendor Devices",
    "0504": "Hayes Microcomputer Products	Vendor Devices",
    "0673": "HCL	Vendor Devices",
    "0943": "HCL Technologies India Private, Ltd	Vendor Devices",
    "0e30": "HeartMath LLC	Vendor Devices",
    "0e30": "HeartMath LLC	Vendor Devices",
    "0fb6": "Heber Ltd	Vendor Devices",
    "0a18": "Heidelberger Druckmaschinen AG	Vendor Devices",
    "06de": "Heisei Electronics Co., Ltd	Vendor Devices",
    "13ea": "Hengstler	Vendor Devices",
    "f003": "Hewlett Packard	Vendor Devices",
    "09d7": "Hexagon NovAtel Inc.	Vendor Devices",
    "0d16": "Hi-Touch Imaging Technologies Co., Ltd	Vendor Devices",
    "09c3": "HID Global	Vendor Devices",
    "1aed": "High Top Precision Electronic Co., Ltd.	Vendor Devices",
    "0c0a": "Highpoint Technologies, Inc.	Vendor Devices",
    "0dd9": "HighSpeed Surfing	Vendor Devices",
    "04b6": "Hint Corp.	Vendor Devices",
    "17cf": "Hip Hing Cable & Plug Mfy. Ltd.	Vendor Devices",
    "3111": "Hiperscan GmbH	Vendor Devices",
    "0d71": "Hirakawa Hewtech Corp.	Vendor Devices",
    "0a47": "Hirose Electric	Vendor Devices",
    "10a0": "Hirotech, Inc.	Vendor Devices",
    "109b": "Hisense	Vendor Devices",
    "0d73": "Hit's Communications, Inc.	Vendor Devices",
    "0503": "Hitachi America, Ltd	Vendor Devices",
    "0ef0": "Hitachi Cable, Ltd	Vendor Devices",
    "0858": "Hitachi Maxell, Ltd	Vendor Devices",
    "0bb8": "Hitachi Semiconductor and Devices Sales Co., Ltd	Vendor Devices",
    "0cd9": "Hitachi Shin Din Cable, Ltd	Vendor Devices",
    "0b37": "Hitachi ULSI Systems Co., Ltd	Vendor Devices",
    "1696": "Hitachi Video and Information System, Inc.	Vendor Devices",
    "1696": "Hitachi Video and Information System, Inc.	Vendor Devices",
    "045b": "Hitachi, Ltd	Vendor Devices",
    "04a4": "Hitachi, Ltd	Vendor Devices",
    "0640": "Hitex Development Tools	Vendor Devices",
    "2e04": "HMD Global	Vendor Devices",
    "0d53": "HMI Co., Ltd	Vendor Devices",
    "067d": "Hohner Corp.	Vendor Devices",
    "0d54": "Holon Corp.	Vendor Devices",
    "1a81": "Holtek Semiconductor, Inc.	Vendor Devices",
    "1243": "Holtek Semiconductor, Inc.	Vendor Devices",
    "04d9": "Holtek Semiconductor, Inc.	Vendor Devices",
    "0c89": "Honda Tsushin Kogyo Co., Ltd	Vendor Devices",
    "12ab": "Honey Bee Electronic International Ltd.	Vendor Devices",
    "10ac": "Honeywell, Inc.	Vendor Devices",
    "105c": "Hong Ji Electric Wire & Cable (Dongguan) Co., Ltd	Vendor Devices",
    "1c89": "HONGKONG WEIDIDA ELECTRON LIMITED	Vendor Devices",
    "0f0d": "Hori Co., Ltd	Vendor Devices",
    "0507": "Hosiden Corp.	Vendor Devices",
    "10d1": "Hottinger Baldwin Measurement	Vendor Devices",
    "03f0": "HP, Inc	Vendor Devices",
    "06fa": "HSD S.r.L	Vendor Devices",
    "0e72": "Hsi-Chin Electronics Co., Ltd	Vendor Devices",
    "1056": "Hsin Chen Ent Co., Ltd	Vendor Devices",
    "0bb4": "HTC (High Tech Computer Corp.)	Vendor Devices",
    "0a19": "Hua Geng Technologies, Inc.	Vendor Devices",
    "0512": "Hualon Microelectronics Corp.	Vendor Devices",
    "04dc": "Huan Hsin Holdings, Ltd	Vendor Devices",
    "214b": "Huasheng Electronics	Vendor Devices",
    "29e2": "Huatune Technology (Shanghai) Co., Ltd.	Vendor Devices",
    "12d1": "Huawei Technologies Co., Ltd.	Vendor Devices",
    "1472": "Huawei-3Com	Vendor Devices",
    "120e": "Hudson Soft Co., Ltd	Vendor Devices",
    "069d": "Hughes Network Systems (HNS)	Vendor Devices",
    "273f": "Hughski Limited	Vendor Devices",
    "256c": "Huion	Vendor Devices",
    "1c27": "HuiYang D & S Cable Co., Ltd.	Vendor Devices",
    "1832": "Huizhou Shenghua Industrial Co., Ltd.	Vendor Devices",
    "675d": "Humanscale	Vendor Devices",
    "1c71": "Humanware Inc	Vendor Devices",
    "0ead": "Humax Co., Ltd	Vendor Devices",
    "02ad": "HUMAX Co., Ltd.	Vendor Devices",
    "0d0e": "Hybrid Networks, Inc.	Vendor Devices",
    "15dc": "Hynix Semiconductor Inc.	Vendor Devices",
    "1025": "Hyper-Paltek	Vendor Devices",
    "2e24": "Hyperkin	Vendor Devices",
    "2ccf": "Hypersecu	Vendor Devices",
    "1951": "Hyperstone AG	Vendor Devices",
    "04db": "Hypertec Pty, Ltd	Vendor Devices",
    "238b": "Hytera Communications	Vendor Devices",
    "0f9c": "Hyun Won, Inc.	Vendor Devices",
    "0435": "Hyundai Electronics America	Vendor Devices",
    "0ac5": "I & C Corp.	Vendor Devices",
    "0b11": "I Tech Solutions Co., Ltd	Vendor Devices",
    "40bb": "I-O Data	Vendor Devices",
    "04bb": "I-O Data Device, Inc.	Vendor Devices",
    "4101": "i-rocks	Vendor Devices",
    "5219": "I-Tetra	Vendor Devices",
    "06ef": "I.A.C. Geometrische Ingenieurs B.V.	Vendor Devices",
    "13dd": "i.Tech Dynamic Limited	Vendor Devices",
    "0a48": "I/O Interconnect	Vendor Devices",
    "0ef2": "I/O Magic Corp.	Vendor Devices",
    "0942": "i2Go.com, LLC	Vendor Devices",
    "04b3": "IBM Corp.	Vendor Devices",
    "0127": "IBP	Vendor Devices",
    "0923": "IC Media Corp.	Vendor Devices",
    "1ae4": "ic-design Reinhard Gottinger GmbH	Vendor Devices",
    "05e8": "ICC, Inc.	Vendor Devices",
    "0aac": "iCompression, Inc.	Vendor Devices",
    "1d03": "iCON	Vendor Devices",
    "1043": "iCreate Technologies Corp.	Vendor Devices",
    "089d": "Icron Technologies Corp.	Vendor Devices",
    "0fe6": "ICS Advent	Vendor Devices",
    "1312": "ICS Electronics	Vendor Devices",
    "0acd": "ID Tech	Vendor Devices",
    "0b81": "id3 Technologies	Vendor Devices",
    "1cb6": "IdeaCom Technology Inc.	Vendor Devices",
    "1391": "IdealTEK, Inc.	Vendor Devices",
    "1fff": "Ideofy Inc.	Vendor Devices",
    "0a85": "Idexx Labs	Vendor Devices",
    "1409": "IDS Imaging Development Systems GmbH	Vendor Devices",
    "0c39": "IFR	Vendor Devices",
    "04e1": "Iiyama North America, Inc.	Vendor Devices",
    "1963": "IK Multimedia	Vendor Devices",
    "222a": "ILI Technology Corp.	Vendor Devices",
    "088e": "iLok	Vendor Devices",
    "1fde": "ILX Lightwave Corporation	Vendor Devices",
    "09eb": "IM Networks, Inc.	Vendor Devices",
    "149a": "Imagination Technologies	Vendor Devices",
    "0c57": "Imaginative Design Operation Co., Ltd	Vendor Devices",
    "0718": "Imation Corp.	Vendor Devices",
    "13d3": "IMC Networks	Vendor Devices",
    "1053": "Immanuel Electronics Co., Ltd	Vendor Devices",
    "0563": "Immersion Corp.	Vendor Devices",
    "07b1": "IMP, Inc.	Vendor Devices",
    "10f1": "Importek	Vendor Devices",
    "058c": "In Focus Systems	Vendor Devices",
    "05ab": "In-System Design	Vendor Devices",
    "0fe4": "IN-Tech Electronics, Ltd	Vendor Devices",
    "10df": "In-Win Development, Inc.	Vendor Devices",
    "0776": "Inalways Corp.	Vendor Devices",
    "0593": "Incite	Vendor Devices",
    "0fb1": "Inclose Design, Inc.	Vendor Devices",
    "08d9": "Increment P Corp.	Vendor Devices",
    "098d": "INDesign	Vendor Devices",
    "081b": "Indigita Corp.	Vendor Devices",
    "073c": "Industrial Electronic Engineers, Inc.	Vendor Devices",
    "19e8": "Industrial Technology Research Institute	Vendor Devices",
    "058b": "Infineon Technologies	Vendor Devices",
    "0bb1": "Infinilink Corp.	Vendor Devices",
    "0c07": "Infinite Data Storage, Ltd	Vendor Devices",
    "2fb0": "Infocrypt	Vendor Devices",
    "0ca7": "Information Systems Laboratories	Vendor Devices",
    "19b6": "Infotech Logistic, LLC	Vendor Devices",
    "102b": "Infotronic America, Inc.	Vendor Devices",
    "06c6": "Infowave Software, Inc.	Vendor Devices",
    "a108": "Ingenic Semiconductor Co.,Ltd	Vendor Devices",
    "601a": "Ingenic Semiconductor Ltd.	Vendor Devices",
    "0b00": "INGENICO	Vendor Devices",
    "0f14": "Ingenico	Vendor Devices",
    "26e2": "Ingenieurbuero Dietzsch und Thiele, PartG	Vendor Devices",
    "0002": "Ingram	Vendor Devices",
    "13fd": "Initio Corporation	Vendor Devices",
    "3333": "InLine	Vendor Devices",
    "11c5": "Inmax	Vendor Devices",
    "0c99": "Innochips Co., Ltd	Vendor Devices",
    "0c3d": "Innocom, Inc.	Vendor Devices",
    "1292": "Innomedia	Vendor Devices",
    "050c": "InnoMedia, Inc.	Vendor Devices",
    "1f75": "Innostor Technology Corporation	Vendor Devices",
    "093d": "InnoSync, Inc.	Vendor Devices",
    "042c": "Innovative Semiconductors, Inc.	Vendor Devices",
    "191c": "Innovative Technology LTD	Vendor Devices",
    "0ec6": "InnoVISION Multimedia, Ltd	Vendor Devices",
    "0cb1": "Innovonics, Inc.	Vendor Devices",
    "2bcc": "InoTec GmbH Organisationssysteme	Vendor Devices",
    "1028": "Inovys Corp.	Vendor Devices",
    "308f": "Input Club	Vendor Devices",
    "1c11": "Input Club Inc.	Vendor Devices",
    "2314": "INQ Mobile	Vendor Devices",
    "160e": "INRO	Vendor Devices",
    "160e": "INRO	Vendor Devices",
    "0648": "Inside Out Networks	Vendor Devices",
    "1608": "Inside Out Networks [hex]	Vendor Devices",
    "a014": "Insignia (Best Buy)	Vendor Devices",
    "135e": "Insta GmbH	Vendor Devices",
    "053c": "Institut of Microelectronic & Mechatronic Systems	Vendor Devices",
    "062c": "Institute for Information Industry	Vendor Devices",
    "0b1f": "Insyde Software Corp.	Vendor Devices",
    "10c6": "Intec, Inc.	Vendor Devices",
    "26bd": "Integral Memory	Vendor Devices",
    "113f": "Integrated Biometrics, LLC	Vendor Devices",
    "0dda": "Integrated Circuit Solution, Inc.	Vendor Devices",
    "0a6c": "Integrated Circuit Systems, Inc.	Vendor Devices",
    "0426": "Integrated Device Technology, Inc.	Vendor Devices",
    "098e": "Integrated Intellectual Property, Inc.	Vendor Devices",
    "08e8": "Integrated Memory Logic	Vendor Devices",
    "1131": "Integrated System Solution Corp.	Vendor Devices",
    "048d": "Integrated Technology Express, Inc.	Vendor Devices",
    "0996": "Integrated Telecom Express, Inc.	Vendor Devices",
    "03e7": "Intel	Vendor Devices",
    "8086": "Intel Corp.	Vendor Devices",
    "8087": "Intel Corp.	Vendor Devices",
    "042b": "Intel Corp.	Vendor Devices",
    "059e": "Intelligent Instrumentation	Vendor Devices",
    "0f6e": "INTELLIGENT SYSTEMS	Vendor Devices",
    "0ad0": "Intellix Corp.	Vendor Devices",
    "09e1": "Intellon Corp.	Vendor Devices",
    "8644": "Intenso GmbG	Vendor Devices",
    "05fd": "InterAct, Inc.	Vendor Devices",
    "0571": "Interex, Inc.	Vendor Devices",
    "0560": "Interface Corp.	Vendor Devices",
    "04df": "Interlink Electronics	Vendor Devices",
    "0cc6": "Intermagic Corp.	Vendor Devices",
    "067e": "Intermec Technologies Corp.	Vendor Devices",
    "0a70": "International Game Technology	Vendor Devices",
    "0a94": "Intersense	Vendor Devices",
    "09aa": "Intersil Corp.	Vendor Devices",
    "0713": "Interval Research Corp.	Vendor Devices",
    "0acf": "Intoto, Inc.	Vendor Devices",
    "0bf1": "Intracom S.A.	Vendor Devices",
    "093c": "Intrepid Control Systems, Inc.	Vendor Devices",
    "0578": "Intrinsix Corp.	Vendor Devices",
    "0537": "Inventec Corp.	Vendor Devices",
    "1e1f": "INVIA	Vendor Devices",
    "3636": "InVibro	Vendor Devices",
    "0cfa": "Inviso, Inc.	Vendor Devices",
    "2ce5": "InX8 Inc [AKiTiO]	Vendor Devices",
    "0dc4": "inXtron, Inc.	Vendor Devices",
    "051f": "IO Systems (Elite Electronics), Inc.	Vendor Devices",
    "0da7": "IOGear, Inc.	Vendor Devices",
    "0f21": "IOI Technology Corp.	Vendor Devices",
    "059b": "Iomega Corp.	Vendor Devices",
    "1c0c": "Ionics EMS, Inc.	Vendor Devices",
    "0622": "Iotech, Inc.	Vendor Devices",
    "1b3b": "iPassion Technology Inc.	Vendor Devices",
    "0b3a": "IPaxess	Vendor Devices",
    "0bc3": "IPWireless, Inc.	Vendor Devices",
    "0c15": "Iris Graphics	Vendor Devices",
    "2420": "IRiver	Vendor Devices",
    "4102": "iRiver, Ltd.	Vendor Devices",
    "1006": "iRiver, Ltd.	Vendor Devices",
    "1953": "Ironkey Inc.	Vendor Devices",
    "6615": "IRTOUCHSYSTEMS Co. Ltd.	Vendor Devices",
    "595a": "IRTOUCHSYSTEMS Co. Ltd.	Vendor Devices",
    "0cf7": "ishoni Networks	Vendor Devices",
    "16b4": "iStation	Vendor Devices",
    "2009": "iStorage	Vendor Devices",
    "348f": "ISY	Vendor Devices",
    "0431": "Itac Systems, Inc.	Vendor Devices",
    "0b7c": "ITRAN Communications, Ltd	Vendor Devices",
    "195d": "Itron Technology iONE	Vendor Devices",
    "04d1": "ITT Canon	Vendor Devices",
    "0d60": "IVL Technologies, Ltd	Vendor Devices",
    "03ec": "Iwatsu America, Inc.	Vendor Devices",
    "07ea": "Iwatsu Electric Co., Ltd	Vendor Devices",
    "0f1d": "Iwill Corp.	Vendor Devices",
    "08d8": "IXXAT Automation GmbH	Vendor Devices",
    "0e26": "J-Phone East Co., Ltd	Vendor Devices",
    "0e26": "J-Phone East Co., Ltd	Vendor Devices",
    "08b8": "J. Gordon Electronic Design, Inc.	Vendor Devices",
    "9ac4": "J. Westhues	Vendor Devices",
    "093e": "J.S.T. Mfg. Co., Ltd	Vendor Devices",
    "16d6": "JABLOCOM s.r.o.	Vendor Devices",
    "1797": "JALCO CO., LTD.	Vendor Devices",
    "14d8": "JAMER INDUSTRIES CO., LTD.	Vendor Devices",
    "0a8e": "Japan Aviation Electronics Industry, Ltd	Vendor Devices",
    "09ab": "Japan Cash Machine Co., Ltd.	Vendor Devices",
    "0aaa": "Japan CBM Corp.	Vendor Devices",
    "0d78": "Japan Distributor Corp.	Vendor Devices",
    "1145": "Japan Radio Company	Vendor Devices",
    "0940": "Japan Storage Battery Co., Ltd	Vendor Devices",
    "0b22": "Japan System Development Co., Ltd	Vendor Devices",
    "087d": "Jaton Corp.	Vendor Devices",
    "0601": "Jazz Hipster Corp.	Vendor Devices",
    "0bc5": "JCN Co., Ltd	Vendor Devices",
    "158e": "JDS Uniphase Corporation (JDSU)	Vendor Devices",
    "0604": "Jean Co., Ltd	Vendor Devices",
    "0a52": "Jebsee Electronics Co., Ltd	Vendor Devices",
    "0979": "Jeilin Technology Corp., Ltd	Vendor Devices",
    "0f30": "Jess Technology Co., Ltd	Vendor Devices",
    "0dbf": "Jess-Link International	Vendor Devices",
    "0dbf": "Jess-Link International	Vendor Devices",
    "0766": "Jess-Link Products Co., Ltd	Vendor Devices",
    "0c6c": "JETI Technische Instrumente GmbH	Vendor Devices",
    "076f": "Jhen Vei Electronic Co., Ltd	Vendor Devices",
    "064c": "Ji-Haw Industrial Co., Ltd	Vendor Devices",
    "e2b7": "Jie Li	Vendor Devices",
    "05af": "Jing-Mold Enterprise Co., Ltd	Vendor Devices",
    "1ba1": "JINQ CHERN ENTERPRISE CO., LTD.	Vendor Devices",
    "0dbe": "Jiuh Shiuh Precision Industry Co., Ltd	Vendor Devices",
    "0dbe": "Jiuh Shiuh Precision Industry Co., Ltd	Vendor Devices",
    "125d": "JMicron	Vendor Devices",
    "152d": "JMicron Technology Corp. / JMicron USA Technology Corp.	Vendor Devices",
    "0e16": "JMTek, LLC	Vendor Devices",
    "0c76": "JMTek, LLC.	Vendor Devices",
    "117e": "JNC, Inc.	Vendor Devices",
    "09e5": "Jo-Dan International, Inc.	Vendor Devices",
    "0c9b": "Jobin Yvon, Inc.	Vendor Devices",
    "1d0a": "Johnson Controls, Inc. The Automotive Business Unit	Vendor Devices",
    "060f": "Joinsoon Electronics Mfg. Co., Ltd	Vendor Devices",
    "2931": "Jolla Oy	Vendor Devices",
    "0bb7": "Joytech Computer Co., Ltd	Vendor Devices",
    "0cd8": "JS Digitech, Inc.	Vendor Devices",
    "0fb2": "Juan-Chern Industrial Co., Ltd	Vendor Devices",
    "08cd": "Jue Hsun Ind. Corp.	Vendor Devices",
    "0631": "JUJO Electronics Corp.	Vendor Devices",
    "0e48": "Julia Corp., Ltd	Vendor Devices",
    "0aff": "Jump Zone Network Products, Inc.	Vendor Devices",
    "138e": "Jungo LTD	Vendor Devices",
    "121e": "Jungsoft Co., Ltd	Vendor Devices",
    "2166": "JVC Kenwood	Vendor Devices",
    "13ca": "JyeTai Precision Industrial Co., Ltd.	Vendor Devices",
    "095c": "K-Tec Electronics	Vendor Devices",
    "24e3": "K-Touch	Vendor Devices",
    "11e6": "K.I. Technology Co. Ltd.	Vendor Devices",
    "17f5": "K.K. Rocky	Vendor Devices",
    "1b59": "K.S. Terminals Inc.	Vendor Devices",
    "184f": "K2L GmbH	Vendor Devices",
    "18d9": "Kaba	Vendor Devices",
    "1c77": "Kaetat Industrial Co., Ltd.	Vendor Devices",
    "13e1": "Kaibo Wire & Cable (Shenzhen) Co., Ltd.	Vendor Devices",
    "17a8": "Kamstrup A/S	Vendor Devices",
    "0be2": "Kanda Tsushin Kogyo Co., Ltd	Vendor Devices",
    "1e1d": "Kanguru Solutions	Vendor Devices",
    "0662": "Kansai Electric Co., Ltd	Vendor Devices",
    "1348": "Katsuragawa Electric Co., Ltd.	Vendor Devices",
    "3197": "Katusha	Vendor Devices",
    "0f54": "Kawai Musical Instruments Mfg. Co., Ltd	Vendor Devices",
    "05e9": "Kawasaki LSI	Vendor Devices",
    "05c1": "Kawasaki Microelectronics, Inc.	Vendor Devices",
    "084e": "KB Gear	Vendor Devices",
    "050f": "KC Technology, Inc.	Vendor Devices",
    "08f8": "Keen Top International Enterprise Co., Ltd	Vendor Devices",
    "2b24": "KeepKey LLC	Vendor Devices",
    "1aad": "KeeTouch	Vendor Devices",
    "05c0": "Keil Software	Vendor Devices",
    "c251": "Keil Software, Inc.	Vendor Devices",
    "8282": "Keio	Vendor Devices",
    "07c1": "Keisokugiken	Vendor Devices",
    "05e6": "Keithley Instruments	Vendor Devices",
    "133e": "Kemper Digital GmbH	Vendor Devices",
    "047d": "Kensington	Vendor Devices",
    "0b28": "Kenwood Corp.	Vendor Devices",
    "098f": "Kenwood TMI Corp.	Vendor Devices",
    "055a": "Kenwood USA	Vendor Devices",
    "0cbe": "Keryx Technologies, Inc.	Vendor Devices",
    "1a12": "KES Co., Ltd.	Vendor Devices",
    "157b": "Ketron SRL	Vendor Devices",
    "0674": "Key Mouse Electronic Enterprise Co., Ltd	Vendor Devices",
    "08c7": "Key Nice Enterprise Co., Ltd	Vendor Devices",
    "0f5f": "Key Technology Corp.	Vendor Devices",
    "0720": "Keyence Corp.	Vendor Devices",
    "2a8d": "Keysight Technologies, Inc.	Vendor Devices",
    "06cd": "Keyspan	Vendor Devices",
    "03f9": "KeyTronic Corp.	Vendor Devices",
    "2f76": "KeyXentic Inc.	Vendor Devices",
    "19db": "KFI Printers	Vendor Devices",
    "107f": "KidzMouse, Inc.	Vendor Devices",
    "0b3e": "Kikusui Electronics Corp.	Vendor Devices",
    "29ea": "Kinesis Corporation	Vendor Devices",
    "16df": "King Billion Electronics Co., Ltd.	Vendor Devices",
    "0d8a": "King Jim Co., Ltd	Vendor Devices",
    "1687": "Kingmax Digital Inc.	Vendor Devices",
    "07cb": "Kingmax Technology, Inc.	Vendor Devices",
    "0f8e": "Kingnet Technology Co., Ltd	Vendor Devices",
    "3057": "Kingsis Corporation	Vendor Devices",
    "1af3": "Kingsis Technology Corporation	Vendor Devices",
    "0951": "Kingston Technology	Vendor Devices",
    "13fe": "Kingston Technology Company Inc.	Vendor Devices",
    "0e56": "Kingston Technology Company, Inc.	Vendor Devices",
    "22cd": "Kinova Robotics Inc.	Vendor Devices",
    "1cac": "Kinstone	Vendor Devices",
    "2def": "Kirale Technologies	Vendor Devices",
    "0d65": "KMJP Co., Ltd	Vendor Devices",
    "0bc0": "Knilink Technology, Inc.	Vendor Devices",
    "055b": "KnowledgeTek, Inc.	Vendor Devices",
    "097b": "Knudsen Engineering, Ltd	Vendor Devices",
    "0f68": "Kobe Steel, Ltd	Vendor Devices",
    "0f68": "Kobe Steel, Ltd	Vendor Devices",
    "0d46": "Kobil Systems GmbH	Vendor Devices",
    "2237": "Kobo Inc.	Vendor Devices",
    "0dd7": "Kocom Co., Ltd	Vendor Devices",
    "040a": "Kodak Co.	Vendor Devices",
    "0564": "Kodak Digital Product Center, Japan Ltd. (formerly Chinon Industries Inc.)	Vendor Devices",
    "0acc": "Koga Electronics Co.	Vendor Devices",
    "0f37": "Kokuyo Co., Ltd	Vendor Devices",
    "0c3b": "Komatsu, Ltd	Vendor Devices",
    "165c": "Kondo Kagaku	Vendor Devices",
    "0bf2": "Konexx	Vendor Devices",
    "04c8": "Konica Corp.	Vendor Devices",
    "132b": "Konica Minolta	Vendor Devices",
    "056f": "Korea Data Systems Co., Ltd	Vendor Devices",
    "17d3": "Korea Techtron Co., Ltd.	Vendor Devices",
    "0944": "KORG, Inc.	Vendor Devices",
    "0832": "Kouwell Electronics Corp.	Vendor Devices",
    "1c02": "Kreton Corporation	Vendor Devices",
    "09d9": "KRF Tech, Ltd	Vendor Devices",
    "0948": "Kronauer music in digital	Vendor Devices",
    "2d25": "Kronegger GmbH.	Vendor Devices",
    "2116": "KT Tech	Vendor Devices",
    "15c8": "KTF Technologies	Vendor Devices",
    "076e": "Kuan Tech Enterprise Co., Ltd	Vendor Devices",
    "1598": "Kunshan Guoji Electronics Co., Ltd.	Vendor Devices",
    "0cc0": "Kuon Yi Industrial Corp.	Vendor Devices",
    "0bfd": "Kvaser AB	Vendor Devices",
    "eb2a": "KWorld	Vendor Devices",
    "10cd": "Kycon, Inc.	Vendor Devices",
    "0458": "KYE Systems Corp. (Mouse Systems)	Vendor Devices",
    "0482": "Kyocera Corp.	Vendor Devices",
    "1184": "Kyocera Elco Corp.	Vendor Devices",
    "0c88": "Kyocera Wireless Corp.	Vendor Devices",
    "0ed2": "Kyoto Micro Computer Co., Ltd	Vendor Devices",
    "1619": "L & K Precision Technology Co., Ltd.	Vendor Devices",
    "20f0": "L3Harris Technologies	Vendor Devices",
    "1949": "Lab126, Inc.	Vendor Devices",
    "0cd5": "LabJack Corporation	Vendor Devices",
    "15c6": "Laboratoires MXM	Vendor Devices",
    "07e8": "Labsystems	Vendor Devices",
    "1020": "Labtec	Vendor Devices",
    "0672": "Labtec, Inc.	Vendor Devices",
    "0747": "Labway Corp.	Vendor Devices",
    "059f": "LaCie, Ltd	Vendor Devices",
    "0b59": "Lake Communications, Ltd	Vendor Devices",
    "0925": "Lakeview Research	Vendor Devices",
    "0da2": "Land Instruments International, Ltd	Vendor Devices",
    "1c10": "Lanterra Industrial Co., Ltd.	Vendor Devices",
    "06d0": "LapLink, Inc.	Vendor Devices",
    "0734": "Lasat Communications A/S	Vendor Devices",
    "0897": "Lauterbach	Vendor Devices",
    "2cc2": "Lautsprecher Teufel GmbH	Vendor Devices",
    "0aa3": "Lava Computer Mfg., Inc.	Vendor Devices",
    "22d4": "Laview Technology	Vendor Devices",
    "041f": "LCS Telegraphics	Vendor Devices",
    "0f11": "LD Didactic GmbH	Vendor Devices",
    "0f23": "Leader Tech Manufacturer Co., Ltd	Vendor Devices",
    "0413": "Leadtek Research, Inc.	Vendor Devices",
    "1eaf": "Leaflabs	Vendor Devices",
    "3344": "Leaguer Microelectronics (LME)	Vendor Devices",
    "f182": "Leap Motion	Vendor Devices",
    "0f63": "LeapFrog Enterprises	Vendor Devices",
    "0ac4": "Leco Corp.	Vendor Devices",
    "05ff": "LeCroy Corp.	Vendor Devices",
    "2c97": "Ledger	Vendor Devices",
    "2b0e": "LeEco	Vendor Devices",
    "1b76": "Legend Silicon Corp.	Vendor Devices",
    "0694": "Lego Group	Vendor Devices",
    "1a98": "Leica Camera AG	Vendor Devices",
    "1711": "Leica Microsystems	Vendor Devices",
    "17ef": "Lenovo	Vendor Devices",
    "2006": "LenovoMobile	Vendor Devices",
    "1dd2": "Leo Bodnar Electronics Ltd	Vendor Devices",
    "0d32": "Leo Hui Electric Wire & Cable Co., Ltd	Vendor Devices",
    "06bf": "Leoco Corp.	Vendor Devices",
    "0c23": "Lernout + Hauspie	Vendor Devices",
    "197d": "Leuze electronic	Vendor Devices",
    "29c2": "Lewitt GmbH	Vendor Devices",
    "05dc": "Lexar Media, Inc.	Vendor Devices",
    "043d": "Lexmark International, Inc.	Vendor Devices",
    "152e": "LG (HLDS)	Vendor Devices",
    "043e": "LG Electronics USA, Inc.	Vendor Devices",
    "1004": "LG Electronics, Inc.	Vendor Devices",
    "05b4": "LG Semicon Co., Ltd	Vendor Devices",
    "0ec0": "LHI Technology (China) Co., Ltd	Vendor Devices",
    "12ba": "Licensed by Sony Computer Entertainment America	Vendor Devices",
    "10af": "Liebert Corp.	Vendor Devices",
    "2766": "LifeScan	Vendor Devices",
    "0dee": "Lifetime Memory Products	Vendor Devices",
    "6244": "LightingSoft AG	Vendor Devices",
    "0977": "Lightsurf Technologies	Vendor Devices",
    "1c7a": "LighTuning Technology Inc.	Vendor Devices",
    "0535": "LIH TZU Electric Co., Ltd	Vendor Devices",
    "0651": "Likom Technology Sdn. Bhd.	Vendor Devices",
    "09a8": "Lin Shiung Enterprise Co., Ltd	Vendor Devices",
    "12d3": "LINAK	Vendor Devices",
    "12d2": "LINE TECH INDUSTRIAL CO., LTD.	Vendor Devices",
    "0e41": "Line6, Inc.	Vendor Devices",
    "0b24": "Link Evolution Corp.	Vendor Devices",
    "3195": "Link Instruments	Vendor Devices",
    "13b1": "Linksys	Vendor Devices",
    "077b": "Linksys	Vendor Devices",
    "066b": "Linksys, Inc.	Vendor Devices",
    "094b": "Linkup Systems Corp.	Vendor Devices",
    "1d6b": "Linux Foundation	Vendor Devices",
    "0e23": "Liou Yuane Enterprise Co., Ltd	Vendor Devices",
    "2df2": "LIPS Corporation	Vendor Devices",
    "0a00": "Liquid Audio	Vendor Devices",
    "1ba2": "Lite Metals & Plastic (Shenzhen) Co., Ltd.	Vendor Devices",
    "0ecd": "Lite-On IT Corp.	Vendor Devices",
    "04ca": "Lite-On Technology Corp.	Vendor Devices",
    "08e5": "Litronic	Vendor Devices",
    "0623": "Littelfuse, Inc.	Vendor Devices",
    "0a4f": "Litton Systems, Inc.	Vendor Devices",
    "18dc": "LKC Technologies, Inc.	Vendor Devices",
    "04c4": "Lockheed Martin Energy Research	Vendor Devices",
    "08f6": "Logic 3 International, Ltd	Vendor Devices",
    "0fa8": "Logic Controls, Inc.	Vendor Devices",
    "0e6f": "Logic3	Vendor Devices",
    "1267": "Logic3 / SpectraVideo plc	Vendor Devices",
    "abcd": "LogiLink	Vendor Devices",
    "d904": "LogiLink	Vendor Devices",
    "0789": "Logitec Corp.	Vendor Devices",
    "046d": "Logitech, Inc.	Vendor Devices",
    "08ce": "Long Well Electronics Corp.	Vendor Devices",
    "0775": "Longshine Electronics Corp.	Vendor Devices",
    "0516": "Longwell Electronics	Vendor Devices",
    "0736": "Lorom Industrial Co., Ltd	Vendor Devices",
    "108e": "Lotes Co., Ltd.	Vendor Devices",
    "106a": "Loyal Legend, Ltd	Vendor Devices",
    "1191": "Loyalty Founder Enterprise Co., Ltd	Vendor Devices",
    "1c31": "LS Cable Ltd.	Vendor Devices",
    "04d4": "LSI Logic, Inc.	Vendor Devices",
    "0bee": "LTK Industries, Ltd	Vendor Devices",
    "0386": "LTS	Vendor Devices",
    "0f9e": "Lucent Technologies	Vendor Devices",
    "0445": "Lucent Technologies, Inc.	Vendor Devices",
    "1759": "LucidPort Technology, Inc.	Vendor Devices",
    "1a7b": "Lumberg Connect GmbH & Co. KG	Vendor Devices",
    "0939": "Lumberg, Inc.	Vendor Devices",
    "1fae": "Lumidigm	Vendor Devices",
    "25e3": "Lumigon	Vendor Devices",
    "1cbe": "Luminary Micro Inc.	Vendor Devices",
    "17b5": "Lunatone	Vendor Devices",
    "1c7b": "LUXSHARE PRECISION INDUSTRY (SHENZHEN) CO., LTD.	Vendor Devices",
    "30c9": "Luxvisions Innotech Limited	Vendor Devices",
    "0ef3": "Lynn Products, Inc.	Vendor Devices",
    "24cf": "Lytro, Inc.	Vendor Devices",
    "0763": "M-Audio	Vendor Devices",
    "08ec": "M-Systems Flash Disk Pioneers	Vendor Devices",
    "249c": "M2Tech s.r.l.	Vendor Devices",
    "1b8f": "MA LABS, Inc.	Vendor Devices",
    "0618": "MacAlly	Vendor Devices",
    "2222": "MacAlly	Vendor Devices",
    "08ae": "Macally (Mace Group, Inc.)	Vendor Devices",
    "0a73": "Mackie Designs	Vendor Devices",
    "08ac": "Macraigor Systems LLC	Vendor Devices",
    "0851": "Macronix International Co., Ltd	Vendor Devices",
    "534d": "MacroSilicon	Vendor Devices",
    "0738": "Mad Catz, Inc.	Vendor Devices",
    "0493": "MAG Technology Co., Ltd	Vendor Devices",
    "120f": "Magellan	Vendor Devices",
    "0711": "Magic Control Technology Corp.	Vendor Devices",
    "2c55": "Magic Leap, Inc.	Vendor Devices",
    "0c1f": "Magicard	Vendor Devices",
    "0801": "MagTek	Vendor Devices",
    "1d88": "Mahr GmbH	Vendor Devices",
    "062e": "Mainsuper Enterprises Co., Ltd	Vendor Devices",
    "eb03": "MakingThings	Vendor Devices",
    "0802": "Mako Technologies, LLC	Vendor Devices",
    "10d4": "Man Boon Manufactory, Ltd	Vendor Devices",
    "0e3b": "Mansella, Ltd	Vendor Devices",
    "081f": "Manta	Vendor Devices",
    "113d": "Mapower Electronics Co., Ltd	Vendor Devices",
    "07fd": "Mark of the Unicorn	Vendor Devices",
    "0f12": "Mars Engineering Corp.	Vendor Devices",
    "0d98": "Mars Semiconductor Corp.	Vendor Devices",
    "07b6": "Marubun Corp.	Vendor Devices",
    "097c": "Marunix Co., Ltd	Vendor Devices",
    "1286": "Marvell Semiconductor, Inc.	Vendor Devices",
    "9e88": "Marvell Semiconductor, Inc.	Vendor Devices",
    "0d7a": "MARX Datentechnik GmbH	Vendor Devices",
    "0d11": "Maspro Denkoh Corp.	Vendor Devices",
    "088b": "MassWorks, Inc.	Vendor Devices",
    "112e": "Master Hill Electric Wire and Cable Co., Ltd	Vendor Devices",
    "1a64": "Mastervolt	Vendor Devices",
    "164c": "Matrix Vision GmbH	Vendor Devices",
    "18ea": "Matrox Graphics, Inc.	Vendor Devices",
    "0986": "Matsushita Electric Works, Ltd.	Vendor Devices",
    "0813": "Mattel, Inc.	Vendor Devices",
    "0a84": "Maui Innovative Peripherals	Vendor Devices",
    "04c3": "Maxi Switch, Inc.	Vendor Devices",
    "0b6a": "Maxim Integrated Products	Vendor Devices",
    "0d49": "Maxtor	Vendor Devices",
    "1682": "Maxwise Production Enterprise Ltd.	Vendor Devices",
    "248a": "Maxxter	Vendor Devices",
    "040e": "MCCI	Vendor Devices",
    "16d0": "MCS	Vendor Devices",
    "0c70": "MCT Elektronikladen	Vendor Devices",
    "09b4": "MDS Telephone Systems	Vendor Devices",
    "09db": "Measurement Computing Corp.	Vendor Devices",
    "086f": "MEC IMEX, Inc.	Vendor Devices",
    "0a67": "Medeli Electronics Co., Ltd	Vendor Devices",
    "05c2": "Media Phonics (Suisse) S.A.	Vendor Devices",
    "095b": "Medialogic Corp.	Vendor Devices",
    "05b7": "Medianix Semiconductor, Inc.	Vendor Devices",
    "0dd3": "MediaQ	Vendor Devices",
    "08ed": "MediaTek Inc.	Vendor Devices",
    "0e8d": "MediaTek Inc.	Vendor Devices",
    "22df": "Medicom MTD, Ltd	Vendor Devices",
    "1113": "Medion AG	Vendor Devices",
    "1513": "medMobile	Vendor Devices",
    "0a21": "Medtronic Physio Control Corp.	Vendor Devices",
    "07b5": "Mega World International, Ltd	Vendor Devices",
    "0d6a": "Megapower International Corp.	Vendor Devices",
    "0e6a": "Megawin Technology Co., Ltd	Vendor Devices",
    "2e57": "MEGWARE Computer Vertrieb und Service GmbH	Vendor Devices",
    "0bed": "MEI	Vendor Devices",
    "1b04": "Meilhaus Electronic GmbH	Vendor Devices",
    "0d61": "Meilu Electronics (Shenzhen) Co., Ltd	Vendor Device"
}

export default vendorIds;